### ISSUE TITLE
Testing - projectile.through

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#1]
**What**
[Wiki link](https://github.com/DeeCaaD/WeaponMechanics-wiki/wiki/Projectile#through)

**Details**
- maximum pass throughs works for entities and blocks
- allow any block / entity works (this overrides ```List``` and ```Whitelist```)
- whitelist and blacklist
- speed modifier

**Can you think of ways to break this feature?**
This should work properly as I tested these pretty well back then, but still requires testing

**Comment by DeeCaaD** [comment]
Fixed and tested

```yaml
    Through:
      Maximum_Through_Amount: 2
      Blocks:
        Default_Speed_Multiplier: 0.75
        Whitelist: false
        List:
          - $GLASS
```
