### ISSUE TITLE
Additional checks during reloading

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#106]
### Description

In order to make it impossible to shoot and/or switch the firing mode during reloading

About reloading stacking (bottommost line) post #85 

### Configuration

```yaml
  Reload:
    Trigger: <trigger serializer>
    Cancel_While_Reloading:
        Shooting: <true/false>
        Selective_Fire: <true/false>
        Scoping: <true/false>
        Reloading: <true/false> #Because reload is stacked   
```
