### ISSUE TITLE
Per-Weapon Toggle for Forced Reload

### ISSUE THREAD

**Issue by WungaWunga** [WeaponMechanics/MechanicsMain#107]
### Description

I'd like to control whether guns automatically reload upon running out of ammo. When you forcibly start loading a slow-to-reload dual wields during a fast-paced fight, you can fire neither the reloading weapon nor your offhand, hobbling the gameplay as your shootout turns into a reloading ceremony. Can we have a setting to control whether each weapon reloads automatically or only upon its reload trigger event (drop key Q)?

### Configuration

```yaml
Reload:
  Enabled: true
  . . .  etc. etc. all other reload settings . . .  
  Reload_Automatically: <true/false>
  etc.
```
