### ISSUE TITLE
Add an "Ignores" toggle for Through: Entities

### ISSUE THREAD

**Issue by WungaWunga** [WeaponMechanics/MechanicsMain#108]
### Description

Using the "Through" property under Projectile settings, we can control whether bullets pass through certain entities, but all entities take the same damage from the projectile fired. Sometimes, a projectile could harm entities differently. A plague cure, for instance, might hurt zombies while leaving the uninfected unharmed. A tranquilizer might only affect non-player entities. And in crowded, plugin-heavy battlefields, a player might need to shoot through passive entities like armor stands, even if his weapon shouldn't necessarily destroy them (e.g., a furniture mod's couch, parked MTVehicles, or sensitive armor stand-based text bubbles). A simple toggle to ignore targets added to the entity list would fix this issue. If lag is a concern, the "Ignores" feature can be disabled globally by default.

### Configuration

```yaml
    Through:
      Entities:
        Whitelist: <true/false>
NEW     Ignores: <true/false> // should projectiles hurt entities on the list or merely pass through them?
        List: <EntityList>
```
