### ISSUE TITLE
Option to do different damage by player or entity

### ISSUE THREAD

**Issue by temoya1** [WeaponMechanics/MechanicsMain#110]
### Description

Option to do different damage by player or entity

### Configuration

```yaml
  Damage:
    Player_Damage: <amount>
    Entity_Damage: <amount>
```
