### ISSUE TITLE
soul binding

### ISSUE THREAD

**Issue by YoyoZhuo** [WeaponMechanics/MechanicsMain#117]
### Description

Hope the weapon can set the soul binding function

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```
