### ISSUE TITLE
1.12.2 Attributes section does not fully work

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#118]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

**I go into the settings of the weapon, set the "GENERIC_MOVEMENT_SPEED" property in the "attributes" section to 10.0, save and use the /wm reload command, but the speed of the player does not change. But it changes when I restart the server. In addition, I set the zoom section to,**
```
    Mechanics:
      Movement:
        Movement_Speed: 1.0
        Towards_Target: false
        Vertical_Speed: 1.0
```
**but when I aim, nothing happens.**

### Expected Behavior

Correct working of attributes section and movement section.

### Steps To Reproduce

1-  I set property "GENERIC_MOVEMENT_SPEED" and property "Movement", save and use /wm reload command

### Frequency

After setting property "GENERIC_MOVEMENT_SPEED" and property "Movement"

### Version and Log

![image](https://user-images.githubusercontent.com/89253304/173373661-5769a6fd-b358-471c-82cd-3efa7468219d.png)

**Comment by TeQTabanca** [comment]
I'm updating the thread. If I set the "GENERIC_MOVEMENT_SPEED" property, save and reload the plugin, my speed will not change if I have the registered weapon, but if I get it again with the /wm give command, it changes. Finally, when players switch to binocular mode, I want their speed to increase a little more, but it doesn't work (for testing purposes).

```
  Attributes:
       - "GENERIC_MOVEMENT_SPEED--0.0338"
  Scope:
    Trigger:
      Main_Hand: "LEFT_CLICK"
      #Off_Hand: "LEFT_CLICK"
    Zoom_Amount: 16
    Mechanics:
      Movement:
       Movement_Speed: 1.0
       Towards_Target: false
       Vertical_Speed: 1.0
```
