### ISSUE TITLE
Block Hit Events

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/MechanicsMain#122]
### Description

A feature that creates destroys / block animations when the projectile hits a block.
Just like Crackshot Plus has features
 Hit_Block:
and
Break_Blocks:

### Configuration

```yaml
  Hit_Block:
    Block_Crack_Animation:
      Minium_Crack: <Integer>
      Maxium_Crack: <Integer>
    Break_Blocks:
      Blacklist: <Boolean>
      Regen_Blocks_After_Milliseconds: <Milliseconds>
      Blocks_List:
         - "GLASS"
```
