### ISSUE TITLE
Add Kill information

### ISSUE THREAD

**Issue by wordangyou** [WeaponMechanics/MechanicsMain#127]
### Description

I hope to add head shot information and ordinary kill information

It is hoped that the information of head shot and common kill can be added to each gun

### Configuration

```yaml
My_Feature:
  Message_Shooter: "Message"
  Message_Victim: "Message"
  etc.
```

**Comment by CJCrafter** [comment]
Already implemented under: https://github.com/WeaponMechanics/MechanicsMain/wiki/Damage

Make sure to join the discord for best support 
```yaml
    Kill:
      Shooter_Mechanics: <MechanicsSerializer>
      Victim_Mechanics: <MechanicsSerializer>
```
