### ISSUE TITLE
Add config.yml to use Armor attribute in lieu of armor types

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/MechanicsMain#139]
### Description

ArmorMechanics allows you to change the amount of armor a material has, but weaponmechanics ignores it. It should have an option to add/subtarct based on the armor attribute. 

```yaml
```

### Configuration

```yaml
Damage:
  Minimum_Rate: 0.5
  Maximum_Rate: 2.0
  Potions:
    DAMAGE_RESISTANCE: -0.05
    WEAKNESS: 0.05
  Armor:
    Per_Attribute_Level: -0.01
```

**Comment by CJCrafter** [comment]
```yaml
Armor_Multipliers:
  Only_Specific_Armor: <true/false> # only use armor based on the damagepoint hit head/chest/legs/feet
  LEATHER: 0.0 # old system stuff... Keep it or get rid of it?
  GOLD: 0.0
  GOLDEN: 0.0 
  CHAIN: 0.0
  IRON: 0.0
  DIAMOND: 0.0
  NETHERITE: 0.0
  HELMET: 0.0
  Per_Level: 0.0 # Checks the player's entity armor attribute + the item's armor attribute (or all armor if Only_Specific_Armor: false)
  Enchantments:
    - protection 0.0
    - projectile_projection 0.0
```
replace the armor section with this, and let people override it per gun for AP
