### ISSUE TITLE
About the "Kill" Feature

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#141]
### Description

The "kill" feature you have made works for every living thing, but if it is done as I will, the "kill" feature can be in advanced options.

### Configuration

```yaml
Kill:
  Players: <true/false>
    Shooter_Mechanics: <MechanicsSerializer>
    Victim_Mechanics: <MechanicsSerializer>
  Mobs: <true/false>
    Shooter_Mechanics: <MechanicsSerializer>
    Victim_Mechanics: <MechanicsSerializer>
    MobNames: (shouldn't be able to see the color codes.)
      "Mob Name":
         Shooter_Mechanics: <MechanicsSerializer>
         Victim_Mechanics: <MechanicsSerializer>
      "LVL 10 Creeper":
         Shooter_Mechanics: <MechanicsSerializer>
         Victim_Mechanics: <MechanicsSerializer>
```
