### ISSUE TITLE
Projectile Curving

### ISSUE THREAD

**Issue by CarboNight** [WeaponMechanics/MechanicsMain#144]
### Description

I think it would be cool to have a setting for projectiles to be able to hook left or right during their flight, with an additional setting for a delay before the hook. This could be very useful for throwable weapons such as throwing stars or boomerangs. The value for "curve" could be between 1.0 and -1.0 where 1.0 is a strong hook to the left and -1.0 is a strong hook to the right, and the value for the delay would be a simple matter of ticks before starting the curve.

### Configuration

```yaml
Curve:
  Curve_Strength: <amount>
  Curve_Delay: <amount>
  etc.
```
