### ISSUE TITLE
Target Block / Button Compatibility

### ISSUE THREAD

**Issue by CarboNight** [WeaponMechanics/MechanicsMain#145]
### Description

It would be great to have a setting for projectiles to be able to interact with target blocks, buttons, or any other redstone type of switch I'm forgetting about just how regular physical projectiles would trigger these objects.

### Configuration

```yaml
Interact_With_Redstone:
  Enable: <true/false>
  Whitelist:
    List:
      - <target_block>
      - <button>
      - <some other thing i'm forgetting>
```
