### ISSUE TITLE
Make Delay_between_shot per weapon not globally

### ISSUE THREAD

**Issue by legendwarz** [WeaponMechanics/MechanicsMain#148]
### Description

i have a problem i made 2 thing gun and medkit
i put delay_between_shot to medkit 120 ticks
after i shot a gun i cant use medkit because they link delay_between_shot
unlink crackshot after i shot a gun i can use medkit and after 120 ticks i can use medkit again

In CS that is slot based I need to those options work per weapon title instead of globally
Thank you

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```
