### ISSUE TITLE
An attractive projectile to make Black Hole guns

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#162]
### Description

A way to add a sort of an "attractive projectile" that every _Attraction_delay_ ticks attract entities to itselfs in a range selector similar to explosion and a way to call an explosion defining it in the same section or adding a new Detonation.Impact_When section like _Attraction_

### Configuration

```yaml
Attractive:
  Delay: <ticks> #Delay from an attraction to another
  Strength: <amount> #A sort of way to define how many MAX_BLOCKS should the entity been pushed every time. If it is negative, it push back entities, if it is positive, it attracts entities
  Attraction_Exposure: <None/Distance> 
  Attraction__Shape: <Sphere/Cube/Parabola>
  Attraction_Type_Data:
      Radius: <Double>
      Angle: <Double>
      Depth: <Double>
      Width: <Double>
      Height: <Double>
  Blacklist:
  - <Entity_Type> #Entity to not attract
  Entity_List:
  - <Entity_Type> #Entity to attract


Explosion:
  Detonation:
    Impact_When: 
      Attraction: <true/false>  #Everytimes there is an attraction
  
```

**Comment by Herobrine15432** [comment]
Oh, let me change a little thing in config, it can be implemented in explosion:

```yaml
Attractive:
  Trigger:
    Timer: <ticks> #A continue attraction while the projectile is alive delayed by this ticks amount
    Explosion: <true/false> #Active the Attraction after an explosion but the explosion MUSTN'T have Detonation.Impact_When.Attraction on true or it will create a loop 
  Strength: <amount> #A sort of way to define how many MAX_BLOCKS should the entity been pushed every time. If it is negative, it push back entities, if it is positive, it attracts entities
  Attraction_Exposure: <None/Distance> 
  Attraction__Shape: <Sphere/Cube/Parabola>
  Attraction_Type_Data:
      Radius: <Double>
      Angle: <Double>
      Depth: <Double>
      Width: <Double>
      Height: <Double>
  Blacklist:
  - <Entity_Type> #Entity to not attract
  Entity_List:
  - <Entity_Type> #Entity to attract


Explosion:
  Detonation:
    Impact_When: 
      Attraction: <true/false>  #Everytimes there is an attraction from this projectile
  ```

**Comment by DeeCaaD** [comment]
Just copypasting these from message I sent in discord

```
If he wants to add it, its basically just adding support for making constant explosions at projectile location. Because `Movement` mechanic already supports that (TARGET_LOCATION in castdata)
+ generally adding support for blacklisted / whitelisted entities and blocks in any explosion

So what would need to be added is something like:
```
```yml
Explosion:
  ...
  Detonation:
    Ticks: <ticks> # detonate every x ticks
  ...
  Blocks:
    Whitelist: <true/false>
    List:
      - <Material>
      - <etc.>
  Entities:
    Whitelist: <true/false>
    List:
      - <EntityType>
      - <etc.>
  ...
```
```
-> `Remove_Projectile_On_Detonation` should not be used with it and using projectile's `Maximum_Travel_Distance | Maximum_Alive_Ticks` to remove the projectile 

```
