### ISSUE TITLE
Horizontal distance for damage drop-offs 

### ISSUE THREAD

**Issue by galacticwarrior9** [WeaponMechanics/MechanicsMain#163]
### Description

An option for damage drop-offs to only consider the horizontal distance travelled by the projectile. 

### Configuration

```yaml
  Damage:
    Use_Horizontal_Distance_For_Dropoff: [false (default)/true] 
    Dropoff:
      - "50~-6.49"
      [...]
```
