### ISSUE TITLE
Weapon Type Feature

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#169]
### Description

**This feature is optional, but I requested it because it is required in some game modes. This feature automatically knocks one down or disables one if the player has more than 2 identical weapons or the same weapon type. Finally, if the same weapon or the same weapon type is on the ground, it will not be given to the player.**

### Configuration

```yaml
Item:
  Weapon_Type: <Custom_Name> | Example: Knife/Pistol/Shotgun/SMG/Rifle/Heavy_Gun/Rocket_Launcher
```

**Comment by CJCrafter** [comment]
Possible implementation:

config.yml:
```yaml
Inventory_Control:
  Deny_Pickup: <true/false> # disables player pickup item event
  Deny_Shoot: <true/false> # denies shooting
  Deny_Click: <true/false> # denies moving items from inventory to inventory
  Categories: # format is: weapon allowed_amount
  - rifle 1
  - melee 1
  - pistol 2
```

Then have an `Inventory_Control` option per weapon to decide which category it belongs to.
