### ISSUE TITLE
Custom Hitbox Adjustment Feature

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#172]
### Description

This feature request will be very necessary as each entity has a separate hitbox. I also think it will be a nice feature in custom mobs.

### Configuration

It might be better if it is added to the file named Entity_Hitboxs.yml. If you ask why I added a custom entity, there is a plugin called [Model Engine](https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-custom-entity-model-manager-1-16-5-1-19-2.79477/).

```yaml
Entity_Hitboxs:
  CREEPER: 
     X: <number>
     Y: <number>
     Z: <number>
Custom_Entity_Hitboxs:
   Custom_Entity_1:
     X: <number>
     Y: <number>
     Z: <number>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Since entity rotations don't qffect the hitbox itself, X and Z should be simplified to `Horizontal`

```yaml
Entity_Hitboxs:
  CREEPER: 
     Horizontal: 0.1
     Vertical: 0.1
```
