### ISSUE TITLE
Underbarrel guns

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#175]
### Description

Basically the Underbarrel gun feature that was in CrackShot, you could switch between 2 guns from 1 gun, while the "underbarrel attachment" was technically a seperate gun.
This was often used to have an underbarrel grenade launcher or something else.
The underbarrel has its own ammo pool, not using the main gun's one, **<<30 | 1>>** as example.

The underbarrel attachment can be coded as its own gun which then can be added to the Underbarrel of another gun, with Mechanics and the option to choose your trigger to switch between main gun and underbarrel gun.

### Configuration

```yaml
Underbarrel:
  Trigger: <TriggerSerializer>
  Switch_Delay: <Ticks> #Delay before you can fire the weapon after switching.
  Mechanics: <MechanicsSerializer>
  Weapon_Attachment: <weapon name>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
