### ISSUE TITLE
Increasing/Decreasing fire rate per shot.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#177]
### Description

A feature that I noticed was part of CSP but not ported over yet to WM.
Basically, when you fire a shot, your fire rate increases/decreases, if you stop firing, it will go back to normal.

The fire rate begins to what you specify your normal fire rate.

Should work as like in CSP, no changes necessary.

### Configuration

```yaml
Increasing_Fire_Rate:
  Add_Rate_Per_Shot: 1
  Minimum_Rate_For_Shot: 1
  Maximum_Rate_For_Shot: 3
  Decrease_Back_to_Starting_Rate:
    Minimum_Milliseconds: 700
    Maximum_Milliseconds: 1000
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
