### ISSUE TITLE
Potion effects affect damage, spread, recoil, fire rate,...

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#179]
### Description

A feature from CSP not present in WM.
Having a certain potion effect with optionally a certain amplifier can affect your gun's performance.
Another option should be included that the potion amplifier can also multiply the effect, and also go in the negative, CSP couldn't decrease stats sadly...

### Configuration

Not entirely sure how this will be configured, so I'll keep it short with damage.
It should also affect fire rate, spread, recoil if the user wants to.

```yaml
My_Feature:
Damage:
  Potions_Affect:
    Head/Torso/Back/...: <Potion>-<Damage increase/decrease>-<Optional: Amplifier>,<etc...>
    Multiply_By_Amplifier: <Integer>
```

If <Optional: Amplifier> is empty, then all amplifiers of that potion effect works.
If 'Multiply_By_Amplifier' is empty, then amplifiers will not increase/decrease damage based on the potion amplifier.

### Payment (optional)

- [ ] I'm willing to pay for this feature
