### ISSUE TITLE
Custom gun durability

### ISSUE THREAD

**Issue by zunkerman** [WeaponMechanics/MechanicsMain#181]
### Description

Ability to set durability amounts per gun. 1 durability removed per shot.

### Configuration

```yaml
Durability:
  breakable: <true/false>
  durability_amount: <amount>
  etc.
```

### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
Even if this is added tomorrow, the `%DURABILITY%` tag in lore will only be added to WeaponMechanicsCosmetics at a later date. Still working on placeholders.

**Comment by CJCrafter** [comment]
Hey @zunkerman, sorry for the wait. DeeCaaD and I are both quite busy.

I can take this commission. Here is what I am thinking:

```yaml
AK-47:
  Shoot:
    Custom_Durability:
      Max_Durability: <number>
      Durability_Per_Shot: <number>  # defaults to 1
      Chance_To_Lose: 50%  # defaults to 100%
      Lose_Durability_Mechanics: <Mechanics>  # If you want to play a sound/send a message when you lose durability
      Break_Mechanics: <Mechanics>  # good for break sounds/particles
```

I am willing to implement this for $25. You can ask if @DeeCaaD offers a better price for the commission. Otherwise, [here is my PayPal link](https://www.paypal.com/paypalme/cjcrafter)
