### ISSUE TITLE
Volume in sounds do not work.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#183]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

No matter what volume you put in, it will always be the same. (I think it defaults to 1)
So making it quieter, or higher for a longer distance does not work, making suppressed guns hard to make.

```
  Shoot:
    Mechanics:
      Sounds:
      - ENTITY_IRON_GOLEM_HURT-4-1.8
```

### Expected Behavior

A lower volume value should play the sound at a lower volume, higher values should do it at max volume with the higher the number, the further it can be heard. (like normal in CrackShot)

### Steps To Reproduce

Use this on a gun, change the "8" to something like 0.1, 0, 2, 4,... it doesn't matter, it won't get quieter or heard from longer distances.

```
  Shoot:
    Mechanics:
      Sounds:
      - ENTITY_IRON_GOLEM_HURT-8-1.8
```

### Frequency

100% of the time.

### Version and Log

![image](https://user-images.githubusercontent.com/29287160/197859000-2558fb90-5c6d-45f2-aee4-11d7ffd56b00.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/9863218/latest.log)
