### ISSUE TITLE
Firearm Action "Pump" is not playing my sounds when Open is missing or a sound delay is over 5.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#185]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Whenever you only use Close in a Pump firearm action, it will not play any of my sounds, open is for some reason required.

Whenever you have any sound that has a delay of over 5, they will not play, but the other sounds work fine.

### Expected Behavior

Pump firearm action should work even if Open or Close is missing, it should atleast have one.
Sounds should play if the delay is longer than 5 on Pump.

### Steps To Reproduce

```
  Firearm_Action:
    Type: pump
    Open:
      Time: 5
    Close:
      Time: 15
      Mechanics:
        Sounds:
        - BLOCK_IRON_DOOR_OPEN-1-1.6
        - BLOCK_PISTON_EXTEND-1-1.6
        - BLOCK_IRON_DOOR_OPEN-1-1.6
        - BLOCK_IRON_TRAPDOOR_OPEN-1-1.6
        - BLOCK_IRON_TRAPDOOR_OPEN-1-1.4
        - BLOCK_IRON_TRAPDOOR_CLOSE-1-1.6
        - BLOCK_IRON_DOOR_CLOSE-1-1.6
        - BLOCK_IRON_DOOR_OPEN-1-1.6-5
        - BLOCK_PISTON_EXTEND-1-1.6-5
        - BLOCK_IRON_DOOR_OPEN-1-1.6-5
        - BLOCK_IRON_TRAPDOOR_OPEN-1-1.6-5
        - BLOCK_IRON_TRAPDOOR_OPEN-1-1.4-5
        - BLOCK_IRON_TRAPDOOR_CLOSE-1-1.6-5
        - BLOCK_IRON_DOOR_CLOSE-1-1.6-5
```

This config should work.
Now try removing this part:

```
    Open:
      Time: 5
```

Now the sounds will not play at all.

For the other bug, try setting maybe all sound with 5 delay to 6 or higher, now they won't play at all.

### Frequency

100% of the time.

### Version and Log

![image](https://user-images.githubusercontent.com/29287160/198326584-030b78d7-1767-400a-87fb-652079e057c6.png)
[latest.log](https://github.com/WeaponMechanics/MechanicsMain/files/9880627/latest.log)

### Anything else?

There are no errors, the previous errors in the logs are just me using the wrong sound format by accident.

Slide and Lever firearm actions does not have this bug.
However, I do not know about Revolver yet.
