### ISSUE TITLE
New firearm action: "Bolt"

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#188]
### Description

I was making a classic World War sniper rifle, thats where I realized a firearm action was missing.
I'm calling it "Bolt"

For shooting, it will: **Shoot -> Open -> Close**
For reloading, it will only just: **Reload**

It will always do this for reloading, no matter if it is empty or not, this is like how Revolver works for reloading.

In real life, you always have to open those classic World War snipers like the Mosin Nagant in order to reload them, you cannot simply just load ammo in there without opening them.
In this way, you can just add the bolting sounds into the reload without causing problems and also keep it future proof for any other weapons that work this way I did not think of yet.

### Configuration

This is basically it, they will only play after shooting, never in reloading.

```yaml
  Firearm_Action:
    Type: bolt
    Open:
      Time: <integer>
      Mechanics:
        Sounds:
        - <MechanicsSerializer>
    Close:
      Time: <integer>
      Mechanics:
        Sounds:
        - <MechanicsSerializer>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
