### ISSUE TITLE
Alternative firearm action idea, recode it to so you can choose your own order.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#189]
### Description

Yes, there's still firearm actions that cannot be done yet, like Issue #188 
We could fix it once and for all if we let players just choose the order on Shooting, Reloading and Empty Reloading however they want.

### Configuration

**Valid actions:** SHOOT, RELOAD, OPEN, CLOSE

SHOOT will not work in Reload_Order and Empty_Reload_Order.
If OPEN and/or CLOSE are before SHOOT, then they should play before you can shoot. _(No idea why you would use this, but its an option I guess)_

```yaml
  Firearm_Action:
    Shoot_Order: <Action 1>-<Action 2>-<Action 3> # Example: Shoot_Order: SHOOT-OPEN-CLOSE
    Reload_Order: <Action 1>-<Action 2>-<Action 3> # Example: Reload_Order: OPEN-RELOAD-CLOSE
    Empty_Reload_Order: <Action 1>-<Action 2>-<Action 3>
    Firearm_Action_Frequency: <use every x amount of shots>
    Open:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>
    Close:
      Time: <ticks>
      Mechanics: <MechanicsSerializer>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
