### ISSUE TITLE
Magazine & ammo feature

### ISSUE THREAD

**Issue by O-FLOYER** [WeaponMechanics/MechanicsMain#194]
### Description

My feature 
1. Magazine won't disappear
 - If I have 2 magazines (All of them are full). When I shot 15 rounds out of my gun in the first magazine and then it will have 15 bullets left. then I switch to the second magazine. So, the first magazine won't disappear. It will keep into my inventory, and it has 15 bullets left. So, I still can use my first magazine again.
 1.1 putting ammo into magazine like reloading weapon. but it's reloading magazine.

2. Add custom damage, armor penetration, etc. to ammo. Everything is like setting damage, armor penetration to weapon, but if my custom ammo has some config of this feature. It will base every value like damage, recoil, spread, armor penetration on ammo not the weapon.

### Configuration

```yaml
  Ammo:
        Base_value_on_ammo: true
        Ammo_Types: "Example1.Ammo_Types,Example2.Ammo_Types,Example3.Ammo_Types,..."
  Reload:
        Keep_magazine_in_inventory_when_reload: true
.
.
.
.
(Default_Ammos) (PS: Just can bring "Shoot" and "Damaga" from weapon to ammo)

762x51mm_30round_magazine:
  Ammo_Types:
    Sniper:
      Item_Ammo:
        Magazine_Item:
          Type: WOODEN_SWORD
          Name: '&f7.62x51mm 30round magazine'
          Lore:
            - '&7_______________________________'
            - '&6Ammo type'
            - '&b+ &f7.62x51mm M61 &cx &f30'
            - '&7_______________________________'
            - '&f30 round, double stack steel magazine'
            - '&ffor a FAL/SA-58 7.62x51 NATO rounds'
          Custom_Model_Data: 9
          Hide_Flags: true
          Deny_Use_In_Crafting: false
        Ammo_Converter_Check:
          Type: true
          Name: true
          Lore: true
  Shoot:
    Projectile_Speed: 630
    Spread:
      Base_Spread: 3.6
      Modify_Spread_When:
        Zooming: 45%
        Sneaking: 45%
        Standing: 45%
        Walking: 120%
        Sprinting: 250%
        In_Midair: 150%
    Recoil:
      Push_Time: 150
      Recover_Time: 200
      Horizontal:
        - 13.5
        - 0
      Vertical:
        - 22.5
      Modify_Recoil_When:
        Zooming: 60%
        Sneaking: 50%
        Standing: 60%
        Walking: 0%
        Sprinting: 250%
        In_Midair: 150%
  Damage:
    Base_Damage: 13
    Armor_Damage: 300
    Head:
      Bonus_Damage: 140
    Body:
      Bonus_Damage: 5
    Arms:
      Bonus_Damage: 3
    Legs:
      Bonus_Damage: 2
    Feet:
      Bonus_Damage: 1
    Dropoff:
      - "50~-1"
      - "100~-2"
      - "125~-3"
      - "150~-4"
      - "175~-5"
      - "200~-6"
      - "225~-7"
      - "250~-8"
      - "300~-10"
      - "350~-12"
      - "400~-14"
.
.
.
.
```

### Payment (optional)

- [X] I'm willing to pay for this feature
