### ISSUE TITLE
Testing - projectile.bouncy

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#2]
**What**
[Wiki link](https://github.com/DeeCaaD/WeaponMechanics-wiki/wiki/Projectile#bouncy)

**Details**
- maximum bounce amount works for entities and blocks
- allow any block / entity works (this overrides ```List``` and ```Whitelist```)
- whitelist and blacklist
- speed modifier

**Can you think of ways to break this feature?**
This should work properly as I tested these pretty well back then, but still requires testing. With larger projectile hitboxes this doesn't always work properly.

**Comment by DeeCaaD** [comment]
Fixed and tested

```yaml
    Bouncy:
      Maximum_Bounce_Amount: 2
      Blocks:
        Allow_Any: true
        Default_Speed_Multiplier: 0.6
      Entities:
        Allow_Any: true
        Default_Speed_Multiplier: 0.6
```
