### ISSUE TITLE
Toxic Damage

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/MechanicsMain#200]
### Description

I'd like to see a sort of "Toxic Damage" Feature
So a way to create a weapon that when hit a player give poison effect to the player and _amount_ damage it every _Delay_ ticks only if his life is at least _minimum_
So for example if _minimum_ is 1 the toxic damage will stop when the player has half heart

### Configuration

```yaml
Toxic_Damage:
    Toxic_Duration: <ticks> #Total duration of the poison effect and of the toxic damage
    Delay_Between_Damage: <ticks> #Ticks delay from one damage to the following one
    Damage_Amount: <int> #Value in HP of damage of singol ToxicDamage
    Minimum_Player_Life: <int> #Value in HP of the minimum player life
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
