### ISSUE TITLE
Explosive Devices

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/MechanicsMain#206]
### Description

Add explosive device, currently only supports timed explosives and impact explosives 

missile - Launches a missile in the air then comes back down at a targeted location/entity (kind of like air strike)
c4 - remote detonation device (gives a “trigger” item)
Landmine - detonates automatically when an entity approaches 

### Configuration

```yaml
Landmine:
  Trigger_Radius: 5.0
  Trigger_Mechanics: <Mechanics>
  Entity_Blacklist:
  - <entity>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
