### ISSUE TITLE
Attempt to save block states on break block.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#212]
### Description

This is only really needed if you want to replace a block with a similar block that has the same block states.
Useful for paint guns to make sure glass panes keep their connections, waterlog state, candles their amount, lit,...

This is only if the "Block break replaced by another block" is similar to the block broken. e.g: GLASS_PANE -> RED_STAINED_GLASS_PANE

### Configuration

```yaml
Cosmetics:
  Block_Damage:
    Attempt_Save_Blockstates: <True/False>
```

### Payment

- [ ] I'm willing to pay for this feature
