### ISSUE TITLE
Mechanics Rewrite 

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/MechanicsMain#213]
### Description

Sometimes, we want to be able to use "universal properties" in mechanics for things like offsets, conditions, repetitions, etc. For example, imagine you wanted to drop bullet shells from different positions depending on whether you were scoping or not. Or you wanted to repeat a potion effect 10 times over 15 seconds for a gas effect.

Fixes #200, #204, #162, #205, #226

Which properties should be universal?
* `targeter`: Allow admins to override the castdata and specify a target (Like, entities in range, for example)
* `conditions`: Allow admins to check each target to see if they pass a certain condition. For example, isScoping
* `repetitions`: Allow admins to repeat the mechanics with a given *interval* and *repeatAmount*
* `offset`: Allow admins to offset the location of the cast relative to the target

### Configuration

This should be an option under every mechanic:
```yaml
Mechanics:
  Particles:
    Particle_1:
      All_Options_Already_From_Particle: "..."
      Repetition:
        Interval: 5
        Amount: 4
      Conditions:
        Is_Player: true
        Is_Scoping: true
      Offset: ~1 1 0
```

we should also consider inline mechanics as a condensed format. For example, the above example could be condensed to:
```yaml
Mechanics:
- particle(sound=flame, offset=~1 1 0, repeatInterval=5, repeatAmount=4) @EntitesInRadius(radius=50) ?isPlayer ?isScoping
```

### Payment (optional)
If you are interested in paying for this feature, please say so below

**Comment by CJCrafter** [comment]
this could also be used for smoke grenades/gas grenades

**Comment by DeeCaaD** [comment]
I assume you refer to this: https://github.com/AtomicZombies/MechanicsInjector

Looking back at that now, it seems pretty good system. While as inline mechanics sounds good at least for me, its simplier to use non-inline for most users. But if both could be (easily) supported its k

**Comment by CJCrafter** [comment]
Every mechanic will have the following options:

expanded format:
```yaml
Mechanic
  Target: "@EntitiesInRadius(radius=10, type=PLAYER)"  # This uses the inline format still since they are simple
  Chance: <ChanceSerializer>  # chance to play the mechanic
  Delay: <ticks>  # time before the mechanic takes effect
  Repeat_Amount: <amount>  # how many times to repeat the mechanic
  Repeat_Interval: <ticks>  # time between repetitions
  
  # Conditions are only checked for each target. For example, if
  # you use "@EntitiesInRadius" then Entity_Type: PLAYER, then
  # the mechanics will only be played for players in the radius
  Conditions:
    Entity_Type: <EntityType>
    Scoping: <DENY/REQUIRED>
    Reloading: <DENY/REQUIRED>
```

In addition, some mechanics (like sound and particle) will have a `sourceLocation` argument. This will allow
you to play the particle per player at a particular location.

#### Targeters
These are some targets I thought of

* `Trigger`
  * How mechanics currently work... targets whoever (or whatever location) caused the mechanic to play  
* `EntitiesInRadius` 
  * Select entities that are close to the cast location
  * Arguments: `radius`
* `NearestEntity`  
  * Select 1 entity that is closest
  * Arguments: `maxDistance`
* `World`
  * Targets every entity in a world
  * Arguments:  `world` (which world to play in, defaults to the trigger's world)
