### ISSUE TITLE
Mechanics summon entities

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#226]
### Description

A mechanic serializer option to summon entities.
This can be used to make mobs, animals and entities like armor stands spawn whenever the mechanics call for it like:

- Spawn a Zombie at the shooter when you reload your gun.
- Spawn a Pig at the block you just shot at.
- Spawn an armor stand with specific NBT at the victim you just killed.

In some way, players can play around with this feature how they want, like making throwable spawn eggs, or a summon staff, or in my case: Use this to make Kill Confirmed gamemodes a thing by making custom armor stands spawn as "tags" whenever you kill a player,...

Below is a configuration idea, with explanation what it should do:

### Configuration

```yaml
Mechanics:
  Summon_Entity:
    Entity: <Entity> #What entity will it spawn? A chicken? a zombie? an armor stand?
    Entity_NBT: <NBT> #What NBT data should the entity carry? anything is possible like {isBaby:true},...
    Amount: <Integer> #How many of this entity should spawn at once, maybe you want a bunch of experience orbs to spawn, or a horde of zombies?
    Spawn_Entity_At: <Shooter / Impact> #Spawns an entity with "Shooter" on the shooter's location when the mechanic fires off, or with "Impact" it spawns an entity where the bullet hit/landed.
    Impact_Rules: <Block / Entity / Both> #When "Spawn_Entity_At" is "Impact", will the entity only spawn when the bullet hits a block, an entity or both?
    Only_Players: <True/False> #When using impact rules, should it only spawn entities when the impacted entity are players?
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
