### ISSUE TITLE
Crawl modifier

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#227]
### Description

hello, there are plugins that create the ability for the player to crawl.  this is done by spawning a block over the player's head, after which he starts "swimming".  like after update 1.13.  Could you make a "Crawl" modifier in the Modify_Spread_When category that would be activated when the player is "swimming" but not in water.

### Configuration

```yaml
Modify_Spread_When:
  Zooming: -5    # Make the gun more accurate when scoping
  Sneaking: -2
  Standing: 0
  Walking: 1.5
  Swimming: 1.5
  In_Midair: 4   # Player is probably jumping, so make them inaccurate
  Gliding: 6     # Player is probably moving super quick, so make them inaccurate
  Crawl: -5 #Player crawling
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
