### ISSUE TITLE
Vanilla Shield

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#228]
### Description

Add shield support for weapons. Weapons currently ignore the shield

### Configuration

```yaml
Shield:
  Ignore_Shield: <true/false>
  Block_Damage: <percent of damage>
  Durability_Loss: <percent of damage>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
