### ISSUE TITLE
Gunfire attract mobs

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#23]
### Description

Easy to explain, an optional feature that turns nearby monsters aggressive towards you when you fire a gun.
Configurable distance is in blocks.
Think of a zombie apocalypse, fire a gun and a ton of zombies nearby will hear that and start following the sound.

Via the upcoming attachments this should be possible to reduce/increase.

### Configuration

```yaml
Shooting_Attract_Mobs:
  Distance: <amount>
  Blacklist: <true/false>
  Entities:
    - "<ENTITY>"
```
