### ISSUE TITLE
Sprinting Skin

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#230]
### Description

Add a "Sprint" skin to a weapon when the player is holding it and starts sprinting.  The "Sprint" skin now applies when the player changes an item in hand to a weapon while sprinting

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
