### ISSUE TITLE
new  modifier Swimming_1-13 and Crawling

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#231]
### Description

Swimming_1-13 - a modifier that only activates if the player is in a water block and in swimming mode added in update 1.13 (player.setSwimming(true)) Currently your Swimming modifier only triggers when the player is in a water block. Please add these two modifiers. Then you will understand why

Crawling - a modifier that activates when the player is in swimming mode added after 1.13 (player.setSwimming(true)) and is not in a water block. Some plugins create the ability to crawl by using the swim mode and sending a block above the player to the player to prevent them from getting up. This is a very useful modifier for servers where there is crawling.

### Configuration

```yaml
Modify_Spread_When:
  Zooming: -5    # Make the gun more accurate when scoping
  Sneaking: -2
  Standing: 0
  Walking: 1.5
  Swimming: 1.5
  In_Midair: 4   # Player is probably jumping, so make them inaccurate
  Gliding: 6     # Player is probably moving super quick, so make them inaccurate
  Crawling: -5 #Player crawling
  Swimming_1-13: 1.5 #Player swimming
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
