### ISSUE TITLE
Grenades/other items work as ammo

### ISSUE THREAD

**Issue by zunkerman** [WeaponMechanics/MechanicsMain#232]
### Description

Need items like grenades for example that can be thrown independently and still function but also work as consumable ammo for guns.

### Configuration

```yaml
Is_ammo?:
  Feature_Option: <true/false>


### Payment (optional)

- [X] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
This was completed in a commission. Using the default config
```yaml
    Ammo:
      Ammo_Types:
        Grenade_Ammo:
          Item_Ammo:
            Bullet_Item:
              Type: RED_CANDLE
              Name: "<gold>Grenade"
            Ammo_Converter_Check:
              Type: true
              Name: true
```
converts the grande to ammo for the gun you add this to
