### ISSUE TITLE
Scope Movment speed

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/MechanicsMain#233]
### Description

Request to add the same capability's as seen in attributes for Generic movement speed, except while zoomed in.

`15$ feature bounty

### Configuration

```yaml
  Scope:
    Attributes:
       - "GENERIC_MOVEMENT_SPEED--0.1000"
```

### Payment (optional)

- [X] I'm willing to pay for this feature
