### ISSUE TITLE
Empty reload features

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#236]
### Description

A seperate reload mechanics that only plays when you are out of ammo, overriding the normal reload duration, ammo per reload and mechanics.

This could be used as a feature for revolvers and stripper fed rifles:

- If you reload a revolver with 3/6 ammo left, you load in each bullet individually. (Current normal reload system plays)
- If you reload a revolver with no ammo left, you load in a speedloader reloading all bullets at once. (New empty reload features)

### Configuration

```yaml
  Reload:
    Trigger: <trigger serializer>
    Magazine_Size: <amount>
    Reloading:          #Rework
      Ammo_Per_Reload: <amount>
      Unload_Ammo_On_Reload: <true/false>
      Reload_Duration: <ticks>
      Shoot_Delay_After_Reload: <ticks>
      Start_Mechanics: <MechanicsSerializer>
      Finish_Mechanics: <MechanicsSerializer>
    Empty_Reloading:          #New
      Ammo_Per_Reload: <amount>
      Unload_Ammo_On_Reload: <true/false>
      Reload_Duration: <ticks>
      Shoot_Delay_After_Reload: <ticks>
      Start_Mechanics: <MechanicsSerializer>
      Finish_Mechanics: <MechanicsSerializer>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
