### ISSUE TITLE
Interaction with interactive blocks

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#237]
### Description

The essence of the option is to check the block for projectiles using raycast (I mean not snowballs and eggs). When you hit a bell or a target, a snowball with an nbt tag that carries an item with Custom Model Data which has an invisible model like this: 

`"{Item:{id:""minecraft:sugar"",Count:1b,tag:{CustomModelData:1}},Motion:[0.1,0.0,0.0]}"`

Here I am using a snowball that will appear as a sugar with custom model data (having an invisible model).

I hope I explained it clearly enough 

Example:
https://imgur.com/a/oXx9iXa and https://imgur.com/a/FaNtgm4

### Configuration

```yaml
InteractiveblocksUse:
    Enabled: True/False
        BlocksList:
            - "Bell" #For example
            - "Target"
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
