### ISSUE TITLE
Weapons Attachments

### ISSUE THREAD

**Issue by Byxis** [WeaponMechanics/MechanicsMain#238]
### Description

I would like to propose a system of attachments to improve certain aspects of a weapon. A system similar to the one in crackshotplus would be perfect!
In addition to crackshotplus, I would like to have a permission to give a weapon upgrade (I never managed to find the permissions on cps ;) )

I know that in this new plugin you want to be as optimized as possible, but I think it's possible to reuse some code.

By the way, I propose on WeaponMecanics and not on WeaponMecanicsCosmetics because I thought it was more appropriate here, but if you decide to release it on WMC it's totally fine with me because I have the plugin too.

Thanks in advance for your answer,
and I wish you a lot of courage if you accept,

Byxis.

### Configuration

```yaml
Attachment:
  Scope:
        Increase_Zoom: <Integer>
        Night_Vision: <Boolean>
        Scope_Affect_Fire_Rate: <Integer>
  Silencer:
        Hide_Trails: <Boolean>
        Reduce_Sound_Volume: <Double>
        Change_Sounds: <String>
        Reduce_Damage: <Double>
        Multiply_Projectile_Speed: <Double>
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
