### ISSUE TITLE
Consistent reloading bar

### ISSUE THREAD

**Issue by yeamiyoyo** [WeaponMechanics/MechanicsMain#239]
### Description

Describe as well as you can about the feature you're requesting

Reloading a weapon manually will show a reloading bar, such as **"Reloading ||||||||||..."**

But when I empty a weapon from shooting and it automatically reloads by itself; instead, it will show **"GUN <30>ᴿ"**

Is it possible to only show the reloading bar instead of the small **"ᴿ"**? I tried changing it in the config but it doesn't work.

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
