### ISSUE TITLE
Choosing which fire mode is the default fire mode.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#24]
### Description

Currently Semi will always be defaulted when a gun is spawned.
This is annoying for automatic weapons to turn them to Auto or Burst everytime they are given.

A simple solution is a simple option to choose which fire mode is the default fire mode.

### Configuration

```yaml
Selective_Fire:
  Trigger: <TriggerSerializer>
  Default: <Fire Mode>
  Mechanics: <MechanicsSerializer>
```
