### ISSUE TITLE
Gunshots and/or impacts create vibrations for Sculk Sensors / Warden

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#241]
### Description

This is kind of half a bug, half a feature request.

Obviously a loud gun shot or bullet impact should alert a Sculk Sensor or Warden.
This was actually the case in CrackShot, but not in WeaponMechanics.
You can even shoot the Warden in Survival and it won't get angry.

But instead of just "Please fix it so WM guns work with vibrations", lets turn it into a feature where silenced guns won't exactly that!

### Configuration

```yaml
  Shoot:
    Shot_Makes_Vibrations: <True/False> #If a gunshot should cause vibrations to nearby Sculk Sensors and Wardens.
  Projectile:
    Projectile_Settings:
      Impact_Makes_Vibrations: <True/False> #If a bullet impact should cause vibrations to nearby Sculk Sensors and Wardens.
  Explosion:
    Explosion_Makes_Vibrations: <True/False> #If an explosion should cause vibrations to nearby Sculk Sensors and Wardens.
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
