### ISSUE TITLE
Recover_Time only after a certain number of consecutive shots.

### ISSUE THREAD

**Issue by ladakx** [WeaponMechanics/MechanicsMain#252]
### Description

Add the ability to run Recover_Time only after a certain number of consecutive shots.

### Configuration

```yaml
  Shoot:
    Recoil:
      Push_Time: 130
      Recover_Time: 330
      Start_Recover_Time_After_Shoots: 3
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
