### ISSUE TITLE
Its fractional penetration by three types of blocks + loss of damage with penetration (DELETED)

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#258]
### Description

Fractional block penetration, i.e. 0.5, 1.7 block for example

Also redo the system of penetration. In the config you specify the conditional units of penetration of the bullet, say 10, make for each list of blocks/blocks different penalties on penetration for 0.1 block. That is, if a bullet enters a block, it loses points of penetration for each 0.1 block. Also loss of damage on piercing (specify per 0.1 block, for example 1 conditional unit per 0.1 block, then the loss will be 10 conditional units for piercing one block), then projectile's config should be about this:

### Configuration

```
Through:
      Maximum_Through_Amount: 10
      Blocks:
        List:
          - "$GLASS" 0 0
          - "$WOOD" 1 1.1
          - "$STONE" 2 1.7
```

### Payment (optional)

- [X] I'm willing to pay for this feature
