### ISSUE TITLE
Play sound when a weapon is selected/unselected in the hotbar.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#26]
### Description

Was a feature on CrackShotPlus, used this on every weapon I made.
Made weapons feel more natural.
It is simple, You scroll through items in your hotbar, when it goes over a weapon recognized by WeaponMechanics, the sounds you have configured for this weapon should play once.
Additional feature request: Sounds for unselecting the weapon.

### Configuration

```yaml
Item:
  Custom_Equip_Sound: <Sound-Volume-Pitch-Delay>,<...>
  Custom_Holster_Sound: <Sound-Volume-Pitch-Delay>,<...>
```
