### ISSUE TITLE
Inheritance of characteristics

### ISSUE THREAD

**Issue by Lerphie** [WeaponMechanics/MechanicsMain#260]
### Description

Inherit characteristics from different configs. For example:

### Configuration

```
usp0:
  Shoot:
    ...: ...
  Reload:
    ...: ...

usp1:
  Shoot: "usp0.Shoot"
  Reload: "usp0.Reload"
  Damage: "usp0.Damage"
  Firearm_Action: "usp0.Firearm_Action"
  Cosmetics: "usp0.Cosmetics"
  Trail: "usp0.Trail"
  Show_Time: "usp0.Show_Time"
```

### Payment (optional)

- [X] I'm willing to pay for this feature
