### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by ootap** [WeaponMechanics/MechanicsMain#27]
### Description

Attachments would be a cool feature to have, just like you had on your crackshotplus plugin. Stuff like supressors, extended clips, scopes and more.

### Configuration

```yaml
##In the weapons config
WEAPON_HERE
Extended_Clip:
  enabled: true
```
Also an attachments folder with the configurable attachments, such as setting how many bullets the extended clip can hold, how much zooms does, sounds etc.
