### ISSUE TITLE
About Bomb Throwing

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#276]
### Description

If the bomb falls 20 blocks away, the player cannot see the bomb. This issue can be resolved by adding the "View-Distance" property.

### Configuration

```yaml
  Projectile:
    Projectile_Settings:
      Type: "DROPPED_ITEM"
      Projectile_Item_Or_Block:
        Type: SLIME_BALL
        Durability: 0
        Unbreakable: true
        View-Distance: <If this feature is not added, it can be set to 50 by default.> (Because a player can see a player 50 blocks away.)
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
