### ISSUE TITLE
high performance projectiles

### ISSUE THREAD

**Issue by MelonHell** [WeaponMechanics/MechanicsMain#278]
### Description

add simplified high-performance projectiles without gravity and speed just ray like in CSGO. this would be a great solution for weak servers, since the entire load from the plugin falls on shells and MSPT grows when shots are fired

### Configuration

```yaml
sniper_rifle:
  Projectile:
    Projectile_Settings:
      Type: "RAY"
      Drag:
        Base: 0.99
        In_Water: 0.96
        When_Raining_Or_Snowing: 0.98
    Through:
      Maximum_Through_Amount: 4
      Entities:
        Allow_Any: true
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
