### ISSUE TITLE
Custom SKIN model on drop

### ISSUE THREAD

**Issue by CristyM96** [WeaponMechanics/MechanicsMain#279]
### Description

Custom SKIN model for dropped item:

photo: https://media.discordapp.net/attachments/1089083651733602344/1089161435294220349/image.png?width=887&height=656

### Configuration

```yaml
 Skin:
    Drop:
      Custom_Model_Data: 99
    Default:
      Custom_Model_Data: 100
    Scope:
      Custom_Model_Data: 101
    Sprint:
      Custom_Model_Data: 102
```

OR

```
  Skin:
    Default:
      Custom_Model_Data: 99
    Handle:
      Custom_Model_Data: 100
    Scope:
      Custom_Model_Data: 101
    Sprint:
      Custom_Model_Data: 102
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
