### ISSUE TITLE
MythicMobs Item Integration

### ISSUE THREAD

**Issue by robotnikthingy** [WeaponMechanics/MechanicsMain#280]
### Description

Interface with the MythicMobs API to allow Weapons and ammo to be dropped as drop from Mythicmobs and MythicMobs drop tables

### Configuration

Configuration will all be handled by MythicMobs. Here is what a drop table from MythicMobs would look like using weapons from WeaponMechanics.

```yaml
ExampleWeaponDropTable:
  TotalItems: 1
  Drops:
  - AK_47 1 0.1
  - Cluster_Grenade 1 0.95
  - STICK 1 0.8
```

### Payment (optional)

- [X] I'm willing to pay for this feature
