### ISSUE TITLE
Placeholders in player head data

### ISSUE THREAD

**Issue by heyy-bbooii** [WeaponMechanics/MechanicsMain#285]
### Description

This would allow you to give the head of the player holding the item

### Configuration

```yaml
    Item:
      Type: "PLAYER_HEAD"
      Skull_Owning_Player: "%player_uuid%"
      Custom_Model_Data: 2
```

### Payment (optional)

- [X] I'm willing to pay for this feature
