### ISSUE TITLE
Damage improvements.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#292]
### A general improvement on how damage works.

First of all, a kill mechanic under every type of damage like Head, Body, Backstab,...
This will fire off if the headshot resulted in the entity dying.

Ontop of that, `Only_Players` is added to make certain mechanics only fire off if the damaged or killed entity was a Player.

Example below will fire off mechanics when a PLAYER is hit by a headshot, and when a PLAYER **dies** to a headshot.

```yaml
  Damage:
    Head:
      Bonus_Damage: 25
      Hit:
        Only_Players: True
        Mechanics: <Mechanics>
      Kill:
        Only_Players: True
        Mechanics: <Mechanics>
```

### Next up is in the main config.

> Armor_Point_Protection

Currently, the Armor attribute does nothing in WeaponMechanics, providing you with 0 protection if you had a custom item with the Armor attribute, or someone added armor points to you with **/attribute**.
Right now, WeaponMechanics only recognizes vanilla armor.

Apparently Minecraft's armor mechanic is pretty complex, with a lot of math behind it, but according to the Minecraft wiki, each armor point should be a 4% reduction in damage, leading to 80% reduction in damage on a full armor bar. (20 armor points).
Individual armor values shouldn't be needed anymore then.

> Damage_Dealt / Damage_Received

These two are now split.
Potions and Enchantments under `Damage_Dealt` will now increase/decrease your damage dealt to entities.
But Potions and Enchantments under `Damage_Received` will increase/decrease your damage taken.

**Strength** in vanilla increases damage by 3 HP and **Weakness** reduces it by 4 HP, I personally think a percentage would be easier like the rest of the damages.
**Resistance** in vanilla reduces all damage taken by 20%, at Level 5 you become invulnerable.

Blast Protection and Projectile Protection work twice as good as Protection in vanilla, but Blast will only work on explosive damage weapons and Projectile on bullet weapons.

### Right now, enchantment and potion effect damage percentages do not stack with levels, which is a shame.

> New format

The new format is:

`Effect: <Double> <Type>`

Effect is replaced by the potion effect or enchantment.

Double is your typical percentage number.

The type is what damage type it is, which can be "ALL" for everything, "BULLET" for normal WeaponMechanics weapons firing bullets, "MELEE" for weapons with `Enable_Melee` set to true, and "EXPLOSIVE" for the explosive damage.

```yaml
Damage:
  Use_Vanilla_Damaging: false
  Minimum_Rate: 0.5
  Maximum_Rate: 100.0
  Damage_Dealt:
    Potions:
      - INCREASE_DAMAGE: 0.3 ALL
      - WEAKNESS: -0.4 ALL
    Enchantments: # in 1.13+, These must use MINECRAFT names... all lowercase
      - SHARPNESS: 0.1 MELEE
      - POWER: 0.1 BULLET
  Damage_Received:
    Armor_Point_Protection: -0.04 ALL
    Potions:
      - DAMAGE_RESISTANCE: -0.2 ALL
    Enchantments: # in 1.13+, These must use MINECRAFT names... all lowercase
      - PROTECTION: -0.04 ALL
      - BLAST_PROTECTION: -0.08 EXPLOSIVE
      - PROJECTILE_PROTECTION: -0.08 BULLET
```

### Ending

There is more that could be talked about.
Such as per-weapon potion/enchant damages that would override the main config list.
But that would get too big and complex for me to write down.

And per-entity damage is left out aswell.

I'm leaving it with this right now.

### Configuration

```yaml
  Damage:
    Head:
      Bonus_Damage: <amount>
      Hit:     #NEW
        Only_Players: <Boolean>
        Mechanics: <Mechanics>
      Kill:     #NEW
        Only_Players: <Boolean>
        Mechanics: <Mechanics>
```
```yaml
Damage:
  Use_Vanilla_Damaging: <Boolean>
  Minimum_Rate: <Double>
  Maximum_Rate: <Double>
  Damage_Dealt:
    Potions:
      - <Potion>: <Double> <Type>
    Enchantments: # in 1.13+, These must use MINECRAFT names... all lowercase
      - <Enchantment>: <Double> <Type>
  Damage_Received:
    Armor_Point_Protection: <Double> <Type>
    Potions:
      - <Potion>: <Double> <Type>
    Enchantments: # in 1.13+, These must use MINECRAFT names... all lowercase
      - <Enchantment>: <Double> <Type>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
