### ISSUE TITLE
Priority of Sprint over Scope skin

### ISSUE THREAD

**Issue by 3Lord3** [WeaponMechanics/MechanicsMain#294]
### Description

I disabled scope while running. But if you first scope, then you can run with an scope
I suggest interrupting the Scope skin while running. While the player is running, the Sprint skinn is played. When it stops, the Scope skin returns if it was enabled

```
  Scope:
    Trigger:
      Main_Hand: "LEFT_CLICK"
      Off_Hand: "LEFT_CLICK"
      Circumstance:
        Sprinting: DENY
```

### Configuration

No

### Payment (optional)

- [ ] I'm willing to pay for this feature
