### ISSUE TITLE
Reworked projectile "through".

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#298]
### Description

Right now, the "Through" feature is a bit annoying how it is set up.

What if I want my bullets to penetrate 5 entities, but only penetrate 1 block? I can't do that.
What if I want my bullets to perfectly penetrate through all glass fine but only once through wood? I can't do that.

The new revamped Block Break system has me thinking that it could be used for "Through" as well.

Below, you can see my proposal of the new Through, by first removing `Maximum_Through_Amount` to allow it being split in entities and blocks.
Then there is `Default_Max_Through_Amount`, which will be the default amount of blocks/entities the projectile can penetrate through if you do not specify a block in the white/blacklist.
And lastly, I added `<through amount>` to the block/entity white/blacklist, so you can specify the projectile being able to pass through a lot of one block, but only a few of another...

### Configuration

```yaml
  Projectile:
    Through:
      #Maximum_Through_Amount: <amount> #REMOVED# 
      Blocks:
        Allow_Any: <true/false>
        Default_Speed_Multiplier: <multiplier>
        Default_Max_Through_Amount: <integer>     #NEW
        Whitelist: <true/false>
        List:
          - <Material>
          - <Material> <speed multiplier> <through amount>
          - <etc.>
      Entities:
        Allow_Any: <true/false>
        Default_Speed_Multiplier: <multiplier>
        Default_Max_Through_Amount: <integer>     #NEW
        Whitelist: <true/false>
        List:
          - <EntityType>
          - <EntityType> <speed multiplier> <through amount>
          - <etc.>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
