### ISSUE TITLE
Testing - projectile.sticky

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#3]
**What**
[Wiki link](https://github.com/DeeCaaD/WeaponMechanics-wiki/wiki/Projectile#sticky)

**Details**
- allow any block / entity works (this overrides ```List``` and ```Whitelist```)
- whitelist and blacklist
- projectile location is updated when entity moves with sticky projectile

**Can you think of ways to break this feature?**
When block is destroyed or entity dies the projectile should drop. When used with stick to entities there should be something like explosive to remove the projectile

**Comment by DeeCaaD** [comment]
Fixed and tested

```yaml
    Sticky:
      Blocks:
        Whitelist: true
        List:
          - $STONE
```
