### ISSUE TITLE
config.yml option to be less strict on build protections with block-break.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#307]
### Description

Currently having any flag on WorldGuard to stop players from griefing will stop WM guns from breaking blocks when they are configurated to do so.
While this is useful for servers like Survivals, it is not very good for shooter minigame servers where normal block breaking is blocked everywhere.

Basically, I want my guns to break glass, but cannot because my maps are protected.

WM's custom weapon break block flag should still be used to deny block breaking even when bypassing is enabled.

### Configuration

```yaml
Something in config.yml:
  Bypass_Grief_Prevention: <true/false>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
```yaml
# Setting this to true will disable compatibility with plugins that use the
# EntityExplodeEvent in their code. You may want to do this if you handle
# compatibility on your own.
Disable_Entity_Explode_Event: false
Disable_Block_Break_Event: false
```

added in next  update.
