### ISSUE TITLE
Block hit mechanic

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/MechanicsMain#309]
### Description

Very simple.

Being able to fire off mechanics when a projectile hits a block.
@Target{} will be the location of the bullet impacting with the block.

Useful for the new Warden Mechanic in WMC, or making per-gun block hit sounds/particles.

### Configuration

```yaml
  Projectile:
    Projectile_Settings:
      Block_Hit_Mechanics:
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
