### ISSUE TITLE
Can't repair guns with repair kits (in repair-kits folder)

### ISSUE THREAD

**Issue by ItsukaHiro** [WeaponMechanics/MechanicsMain#318]
### Current Behavior

Simply not works

### Expected Behavior

Guns has been repaired

### Steps To Reproduce

1. Assign a Repair Kit in repair-kits
2. Make custom durability for a gun
3. Try to repair

### Version and Log

![2023-06-11_17 05 32](https://github.com/WeaponMechanics/MechanicsMain/assets/64533662/2225f68f-c381-4e91-af1f-ab96d3f7fad2)

### Anything else?

Code for Repair Kit:
```yml
Universal_Kits:
  Total_Durability: 3000
  Blacklist: true
  Item:
    Type: IRON_INGOT
    Name: "<yellow>Universal Repair Kits for Combat"
    Lore:
      - "<gray>Drag and drop this onto a weapon to repair it"
  Break_Mechanics:
    - "Sound{sound=ENTITY_ITEM_BREAK, listeners=Source{}}"
```
also, code for weapon, CustomDurability part (in this case, M4A1):
```yml
    Custom_Durability:
      Max_Durability: 180
      Lose_Max_Durability_Per_Repair: 30
      Broken_Item:
        Type: "MOJANG_BANNER_PATTERN"
        Name: "<gold>M4A1 - Broken"
      Break_Mechanics:
        - "Sound{sound=ENTITY_ITEM_BREAK, listeners=Source{}}"
      Repair_Mechanics:
        - "Sound{sound=BLOCK_ANVIL_USE, listeners=Source{}}"
```
https://github.com/WeaponMechanics/MechanicsMain/assets/64533662/c3e434f0-3e84-4dde-a087-19acf256aa31
