### ISSUE TITLE
Allow us to set a base config for weapons and other related items

### ISSUE THREAD

**Issue by yum13241** [WeaponMechanics/MechanicsMain#321]
### Description

Generic stuff like which buttons should scope, default damage, default speed, pretty much any default options.

Specifying them in the weapon specific file would override the generic one, obviously.

### Configuration

Weapons.yaml
```yaml
 Binds:
  Reverse_Fire_And_Scope: true
  Default_Damage: 100
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
