### ISSUE TITLE
Option for keeping reload while using other weapons

### ISSUE THREAD

**Issue by Mauppi** [WeaponMechanics/MechanicsMain#324]
### Description

An optional value in the weapon's config.
If you have it enabled and reload the weapon and change your hotbar to another weapon, it will still keep reloading the weapon which was triggered the reload.

This would enable more arcade style gameplay possibilities. :)

### Configuration

```yaml
WeaponXYZ:
  Options:
    KeepReloadingWhenChanged: <true/false>
```
(I don't remember the exact config format rn haha)

### Payment (optional)

- [ ] I'm willing to pay for this feature
