### ISSUE TITLE
Option to have infinite Ammo.

### ISSUE THREAD

**Issue by yum13241** [WeaponMechanics/MechanicsMain#325]
### Description

There will be 2 options:

Infinite_Mag: <true/false>
Infinite_Reserve: <true/false>

Controlled by a command, to easily toggle. This can be specified in the configuration which will always have priority.

Infinite reserve could be used for kitpvp, for example, so players still have to reload, but won't need constant ammo replenishments. Infinite mag effectively disables reloading, as the player never has to reload. If infinite reserve is off, ammo depletion logic is reversed, causing the ammo reserve to be used up before the mag, to skip reloading. Otherwise you can just skip decreasing the counter.

### Configuration

```yaml
My_Feature:
  Infinite_Mag: <true/false>
  Infinite_Reserve: <true/false>
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
