### ISSUE TITLE
Projectile "Through:" bug

### ISSUE THREAD

**Issue by NarinExceL** [WeaponMechanics/MechanicsMain#328]
### Current Behavior

Projectile "Through:" always through some blocks even if "Blocks:" was not configured.

This issue can be reproduced for all blocks. Full-Block, Non-Solid, Liquid, etc.

When I removed "Through:" section, this issue was not reproduced.

### Expected Behavior

When "Blocks:" was not configured, the projectile should not go through any blocks.

### Steps To Reproduce

1. Use this config ("Maximum_Through_Amount: -1" can be replaced to any numbers that can be used)
```yaml
Projectile:
    Projectile_Settings:
      Type: INVISIBLE
      Gravity: 0.0
      Maximum_Travel_Distance: 200
    Through:
      Maximum_Through_Amount: -1
      Entities:
        Allow_Any: true
```
2. As you can see, there is not "Blocks:" section in that configure.
3. Spawn the weapon and shoot
4. The Projectile will allways through blocks even if "Blocks:" is not configured.

### Version and Log

![image](https://github.com/WeaponMechanics/MechanicsMain/assets/136104013/1b5bbc2a-80a3-430a-919a-13fe38d3762f)

### Anything else?

Reproduction Video: https://streamable.com/nzf43r
