### ISSUE TITLE
Better dual-wielding support

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#33]
### Description

Describe as well as you can about the feature you're requesting
- weapon info display integration
- trigger dual wield support
- modify spread and recoil when dual-wielding support

### Configuration

- weapon info display integration
```yaml
    Weapon_Info_Display:
      Action_Bar:
        Message: <string>
        Time: <ticks>
      Title:
        Title: <string>
        Subtitle: <string>
        Time: <fade in ticks>-<stay ticks>-<fade out ticks>
      Boss_Bar:
        Title: <string>
        Bar_Color: <string>
        Bar_Style: <string>
        Time: <ticks>
      Update_Item_Name: <true/false>
      Show_Ammo_In:
        Boss_Bar_Progress: <true/false>
        Exp_Level: <true/false>
        Exp_Progress: <true/false>
      Dual_Wielding:
        Action_Bar_Message: <string>
        Title: <string>
        Subtitle: <string>
        Boss_Bar: <string>
```
```yaml
Placeholder_Symbols:
  Dual_Wield_Separator: " &7| "
```

- trigger dual wield support
```yaml
  Trigger:
    Main_Hand: right_click
    Off_Hand: right_click
    Dual_Wield:
      Main_Hand: right_click
      Off_Hand: left_click
```

- modify spread and recoil when dual-wielding support
```yaml
      Modify_Spread_When + recoil + increasing spread:
        Zooming: <amount> or <amount>%
        Sneaking: <amount> or <amount>%
        Standing: <amount> or <amount>%
        Walking: <amount> or <amount>%
        Swimming: <amount> or <amount>%
        In_Midair: <amount> or <amount>%
        Gliding: <amount> or <amount>%
        Dual_Wielding: <amount> or <amount>%
```
