### ISSUE TITLE
Reload Animation

### ISSUE THREAD

**Issue by SGBdoya** [WeaponMechanics/MechanicsMain#331]
### Description

In the Skins feature, if one wishes the gun reloading model to be an animated model (mcmeta), there exists the issue of the animation not necessarily starting from the beginning (since Minecraft's ticks are constantly running). Therefore, I hope there can be a feature that allows for continuous switching of Custom Model Data. Alternatively, if there are other methods, please let me know. Thank you.

### Configuration

```yaml
Skin:
    Reload:
        Type: <Material>
        Custom_Model_Data_Animation: 3 <number of frame>
            Frame_1: <Integer> -delay <Integer>
            Frame_2: <Integer> -delay <Integer>
            Frame_3: <Integer> -delay <Integer>
      
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
