### ISSUE TITLE
Flinch during ADS

### ISSUE THREAD

**Issue by HMS-CV-Unicorn** [WeaponMechanics/MechanicsMain#332]
### Description

How about adding a "flinch" when got shot?
When attacked, the screen turns upward and the aim is disrupted.
I think adding this effect to sniper rifles would allow for more tactical combat.

Sorry for my bad English, I translated it using deepl

### Configuration

```yaml
Damage:
  Flinch: <amount>
  Flinch_Resistance: <amount>
  etc.
```

### Payment (optional)

- [X] I'm willing to pay for this feature
