### ISSUE TITLE
Support for Display Entities

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/MechanicsMain#335]
### Description

Display Entities in any capacity!!

As a projectile? :D 
As a mechanic? :o 
As a new Cosmetic feature? O_o

![2023-03-17_21 23 20](https://github.com/WeaponMechanics/MechanicsMain/assets/23036913/3bb92ee5-c247-49cf-8bac-afda59af8fef)

### Configuration

```yaml
Projectile:
  Type: Display_entity {}
  Delete-Server: True
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
