### ISSUE TITLE
Explosion mechanics use location of weapon user rather than explosion origin

### ISSUE THREAD

**Issue by galacticwarrior9** [WeaponMechanics/MechanicsMain#338]
### Current Behavior

When using explosion mechanics, the mechanics originate from the current position of the weapon's user.

Here is a [video](https://streamable.com/wg6zat).

### Expected Behavior

The mechanics originate from explosion origin.

### Steps To Reproduce

1. Use this config:
```yaml
SmokeGrenade:
  Info:
    Weapon_Item:
      Type: "WOODEN_SWORD"
      Name: "<gradient:#BEBEBE:#A2A2A2>Test Grenade"
      Lore:
        - "&7A test"
      Unbreakable: true
      Hide_Flags: true
      Deny_Use_In_Crafting: true
    Weapon_Equip_Mechanics:
      - Sound{sound=ITEM_BUNDLE_REMOVE_ONE, volume=1, pitch=0.5, noise=0.1, listeners=Source{}}
    Weapon_Holster_Mechanics:
      - Sound{sound=ITEM_BUNDLE_INSERT, volume=1, pitch=0.5, noise=0.1, listeners=Source{}}
  Skin:
    Default:
      Custom_Model_Data: 718
  Projectile:
    Projectile_Settings:
      Type: "ARMOR_STAND"
      Projectile_Item_Or_Block:
        Type: "WOODEN_SWORD"
        Custom_Model_Data: 718
      Disable_Entity_Collisions: true
    Bouncy:
      Maximum_Bounce_Amount: 3
      Blocks:
        Allow_Any: true
        Default_Speed_Multiplier: 0.6
      Rolling:
        Required_Motion_To_Start_Rolling: 6
        Blocks:
          Allow_Any: true
          Default_Speed_Multiplier: 0.7
          List:
            - "$_ICE-0.99"
            - "ICE-0.99"
  Shoot:
    Trigger:
      Main_Hand: "RIGHT_CLICK"
      Off_Hand: "RIGHT_CLICK"
      Deny_When:
        Swimming: false
    Projectile_Speed: 18
    Delay_Between_Shots: 20
    Consume_Item_On_Shoot: true
    Mechanics:
      - CustomSound{sound=grenade_arm, volume=0.5, pitch=1, noise=0.1}
      - CustomSound{sound=grenade_throw, volume=0.5, pitch=1, noise=0.1}
  Explosion:
    Disable_Vanilla_Knockback: true
    Explosion_Exposure: "DEFAULT"
    Explosion_Shape: "SPHERE"
    Explosion_Type_Data:
      Radius: 8
    Detonation:
      Delay_After_Impact: 40
      Remove_Projectile_On_Detonation: true
      Impact_When:
        Block: true
    Mechanics:
      - "CustomSound{sound=smoke_emit, volume=4, pitch=1, noise=0.1, listenerConditions=[Range{max=32}]} @Target{}"
      - "Particle{particle=EXPLOSION_NORMAL, repeatAmount=20, repeatInterval=8} @Sphere{points=500, radius=8}"
  Cosmetics:
    Splash_Mechanics:
      - "Sound{sound=ENTITY_GENERIC_SPLASH, volume=1, pitch=1.85, noise=0.15} @Target{}"
      - "Particle{particle=WATER_SPLASH, count=20, noise=0.2 0.2 0.2} @Target{}"

```

2. Spawn the weapon and throw it. 
3. Once the particles begin spawning, move. Observe how the particles follow you.

### Version and Log

[Log](https://mclo.gs/ghLi4he). Nothing of note there though.

`/wm info` dump:

```yaml
[18:32:11 INFO]: WeaponMechanics, v2.5.9
[18:32:11 INFO]:   ➢ Authors: DeeCaaD, CJCrafter
[18:32:11 INFO]:   ➢ Command: /weaponmechanics
[18:32:11 INFO]:   ➢ Server: Purpur git-Purpur-2015 (MC: 1.20.1)
[18:32:11 INFO]:   ➢ MechanicsCore: 2.4.5
[18:32:11 INFO]:   ➢ Java: 17.0.7
[18:32:11 INFO]:   ➢ Supported plugins: ViaVersion
```
