### ISSUE TITLE
Melee

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#34]
### Description

Describe as well as you can about the feature you're requesting

### Configuration

```yaml
  Melee:
    Enable_Melee: <true/false>
    Melee_Attachment: <melee weapon name>
    Melee_Range: <maximum melee range>
    Melee_Hit_Delay: <ticks>
    Consume_Ammo_On_Hit: <true/false>
    Melee_Miss:
      Mechanics: <MechanicsSerializer>
      Melee_Miss_Delay: <ticks>
      Consume_Ammo_On_Miss: <true/false>
```
