### ISSUE TITLE
A Command that would load the resource pack for you

### ISSUE THREAD

**Issue by Vaskel01** [WeaponMechanics/MechanicsMain#344]
### Description

Similar to the command "/oraxen pack send <player name>" from oraxen, there would be a command that would loads the resource pack for the player, so they don't have to rejoin the server to have the resource pack to re-load again. 

### Configuration

```yaml
send_pack:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
