### ISSUE TITLE
Mechanics that will activated when finish equipping

### ISSUE THREAD

**Issue by usamaru64** [WeaponMechanics/MechanicsMain#348]
### Description

This Mechanics will activated when finish equip.
It will not activated if switching items during equipping.

### Configuration

```yaml
Info:
  Weapon_Equip_Mechanics: <Mechanics>
  Weapon_Equip_Finish_Mechanics: <Mechanics>
  Weapon_Equip_Delay: <Amount>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
What's the use case for this?

**Comment by usamaru64** [comment]
I want to create something like authentication

```YAML
  Info:
    Weapon_Equip_Mechanics:
    - Title{title=<green>Authentication Complete, fadeIn=5, stay=10, fadeOut=5, delayBeforePlay=65}
    Weapon_Equip_Delay: 60
  Show_Time:
    Weapon_Equip_Delay:
      Title: "<red>Authentication in progress..."
      Subtitle: "<gray>%bar% <gray>%time%s"
      Bar:
        Left_Color: "<green>"
        Right_Color: "<red>"
        Left_Symbol: "| "
        Symbol_Amount: 15
```

In this case, the title would appear after 3.125 seconds, even if the item was switched in the middle of the session.
