### ISSUE TITLE
Mechanics of when the weapon scope is opened and the scope is not opened.

### ISSUE THREAD

**Issue by Kugana** [WeaponMechanics/MechanicsMain#366]
### Description

particles are generated is more detailedly divided into when the weapon scope is opened and when the scope is not opened, that can better create the effect of muzzle flash.

### Configuration

```yaml
Shoot:
  scope:
    Mechanics:
      - "Particle{particle=COMPOSTER, count=1} @Source{eye=true, offset=~0 -0.08 0.7}"
```

### Payment (optional)

- [x] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
what are you asking for exactly?

**Comment by Kugana** [comment]
now Mechanics just can set when you shot, but the weapon model has classified default and scope, so when I shoot in default,
the particle location is strange, it was same location of scope shoot
sorry my english is bad

**Comment by CJCrafter** [comment]
```yaml
Shoot:
  Mechanics:
    - "Particle{particle=COMPOSTER, count=1} @Source{eye=true, offset=~0.4 -0.1 0.7} ?IsScoping{inverted=true}"
    - "Particle{particle=COMPOSTER, count=1} @Source{eye=true, offset=~0 -0.08 0.7} ?IsScoping{}"
```
