### ISSUE TITLE
Option to reload guns on death

### ISSUE THREAD

**Issue by NetheriteKnight** [WeaponMechanics/MechanicsMain#37]
### Description

An option to reload the player's guns when they die.

### Configuration

```yaml
Reload_on_death:
  Enabled: <true/false>
  Blacklist:
  - <gun_name>
  - <gun_name>
```

**Comment by CJCrafter** [comment]
This will go in the `config.yml`. Need to fix the 

```yaml
Reload_Guns_In_Inventory_After_Death:
  Enabled: <true/false> # false by default
  Requires_Group: NONE # Check the group of the player, required vault to be installed to work.
  Requires_Permission: NONE # Leave blank, or type 'NONE' to require no permission
  World_Blacklist: <true/false> # false by default
  World_List:
    - world_nether
    - world_the_end
  Weapon_Blacklist: <true/false>
  Weapon_List:
  - ak-47
  - m4a4
```
