### ISSUE TITLE
Trail sound for MP or MG (PAY FEATURE)

### ISSUE THREAD

**Issue by MatsCraft1** [WeaponMechanics/MechanicsMain#372]
### Description

Description:
When shooting an MP or MG the shots sound very "short" but the last one tends to echo and ring out.
This could be simulated by adding a "trail" sound after a row of shots. This could be checked for if the player releases the mouse button and doesn't hold it down to shoot any more, or only taps it once, it will play the trail sound instead of the usual shot sounds.

Another fitting idea would be an alternative option for gun shot sounds. Players nearby would hear the usual sound of the gun but far away players would hear more immersive sounds the resource pack creator used a low-pass filter on.

### Configuration

```yaml
immersive_sounds:
  trail_sound: <true/false>
  alternative_distant_shot: <true/false>
      distant_shot_sound:
      - "CustomSound{sound=gun.mp40.fire.trail, volume=1}"
```

### Payment (optional)

- [X] I'm willing to pay for this feature
