### ISSUE TITLE
Delay before shot is fired after pulling trigger

### ISSUE THREAD

**Issue by yernaiaaa** [WeaponMechanics/MechanicsMain#386]
### Description

This would be an option to configure a delay before the projectile is spawned and the shoot mechanics are triggered when you activate the gun. Would also be great if we could configure mechanics that are triggered at the start of the delay.

Would be useful for flintlocks and such

### Configuration

```yaml
Pre_Shoot:
  Pre_Shoot_Delay: <Ticks>
  Mechanics: <Mechanics>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
