### ISSUE TITLE
[weaponmechanicsplus] i wish camera recoil attachment 

### ISSUE THREAD

**Issue by herojaecheol** [WeaponMechanics/MechanicsMain#391]
### Description

There seems to be an attachment that controls [spread], but there is no attachment that controls [camera recoil].
Thank you for creating a good plugin.

### Configuration

```yaml
  Shoot_Modifier:
      Horizontal:
        - <horizontal recoil>
        - <etc.>
      Vertical:
        - <vertical recoil>
        - <etc.>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
