### ISSUE TITLE
 Shielding parameter in the Damage_Modifiers section not work

### ISSUE THREAD

**Issue by yngdrms** [WeaponMechanics/MechanicsMain#392]
### Current/Expected Behavior

I tried setting the Shielding parameter both in the main plugin configuration under Damage_Modifiers and in the individual weapon configuration. When I set this parameter to -100% nothing happens and the damage stays the same even when using a shield, but when I set +100% the damage increases.

### Steps To Reproduce

-

### Log File

-

**Comment by CJCrafter** [comment]
please do testing next time. It works just fine, you just haven't set the modifier high enough

**Comment by yngdrms** [comment]
> please do testing next time. It works just fine, you just haven't set the modifier high enough
Here's the config section with that setting and the damage through the shield still goes through.
```
  Damage:
    Base_Damage: 14
    Armor_Damage: 6
    Damage_Modifiers:
      Min: 20%   # Bullets will always do at least 20% of their base damage
      Max: 250%  # Bullets will, at a max, do 300% of their base damage
      Per_Armor_Point: -5%
      Enchantments:
        - projectile_protection -8%
        - protection -4%
      Head: +50%
      Body: +0%
      Arms: -20%
      Legs: -20%
      Feet: -50%
      Back: +20%
      Shielding: -100%
```
