### ISSUE TITLE
Better Recoil

### ISSUE THREAD

**Issue by HMS-CV-Unicorn** [WeaponMechanics/MechanicsMain#396]
### Description

Make a slight zoom magnification change to the gun's recoil.
This makes the visual of recoil more realistic.

The current configuration of recoil is realized by a two-dimensional movement of the viewpoint in the vertical and horizontal directions.
By using this change in zoom magnification, it will be possible to produce more three-dimensional recoil and shaking.

### Configuration

```yaml
Recoil:
      Push_Time: <push time in millis>
      Recover_Time: <recover time in millis>
      Depth:
        - <recoil depth>
      Horizontal:
        - <horizontal recoil>
        - <etc.>
      Vertical:
        - <vertical recoil>
        - <etc.>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
