### ISSUE TITLE
 Testing - projectile.projectile_motion

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#4]
**What**
[Wiki link](https://github.com/DeeCaaD/WeaponMechanics-wiki/wiki/Projectile#projectile_motion)

**Details**
- gravity
- minimum and maximum speed works and removing them based on it also works
- motion decreases work based on circumstances

**Can you think of ways to break this feature?**
No

**Comment by DeeCaaD** [comment]
Tested

```yaml
    Projectile_Settings:
      ...
      Gravity: 0.05
      Minimum:
        Speed: 10
        Remove_Projectile_On_Speed_Reached: false
      Maximum:
        Speed: 30
        Remove_Projectile_On_Speed_Reached: false
      Decrease_Motion:
        Base: 0.99
        In_Water: 0.96
        When_Raining_Or_Snowing: 0.98
      Disable_Entity_Collisions: true
```
