### ISSUE TITLE
rpg backblast

### ISSUE THREAD

**Issue by unboxedfrog** [WeaponMechanics/MechanicsMain#406]
### Description

RPG backblast (When shooting a rpg, anyone standing behind gets damaged)

### Configuration

```yaml
Shoot:
  Mechanics:
  - Shoot(rpg.projectile.backblast)
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
