### ISSUE TITLE
Regarding damage cause support in the latest version of Weapon Mechanic

### ISSUE THREAD

**Issue by herojaecheol** [WeaponMechanics/MechanicsMain#418]
### Description

I am using [weaponmechanics] on my server and experiencing amazing quality.
However, starting from version 3.3.0, [death event] did not display the attacker and it was found out that this was due to damage cause.
Could you please support this?

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment (optional)

- [x] I'm willing to pay for this feature
