### ISSUE TITLE
Mythicmobs addon

### ISSUE THREAD

**Issue by TeslaGM** [WeaponMechanics/MechanicsMain#42]
### Description

An addon for permits to shoot/throw grenate/use melee weapon to mobs in Mythicmobs with an addon for Mythicmobs

### Configuration

(In mythicmobs)
Enable_WM_Gun: <T/F>
Gun: <ID>
Switch_Gun_When_No_Ammo: <T/F>
Sec_Gun: <ID>

**Comment by CJCrafter** [comment]
Added the actual guns to Mythic Mobs would be a terribly difficult task, since we would need to add AI and such. Instead we may simply add a `weaponMechanicsShoot` mechanic. Consider the following from the MythicMobs wiki:
```yaml
FieryZombie:
  Type: ZOMBIE
  Display: 'Fiery Zombie'
  Health: 50
  Skills:
  - mechanic1
  - skill{skill=Skill1}
  - skill{s=Skill2}
  - skill:Skill3
  
  # WeaponMechanics will add a shoot skill here
  - weaponMechanicsShoot(weapon=AK-47) @target ~onTimer(100) 0.5 # 50% chance to shoot bullet at entity target every 5 seconds
  - weaponMechanicsShoot(weapon=AK-47, hSpread=1, vSpread=hSpread) # Add 1 block spread
```
That way we could let people use multiple weapons and customize targeters and such.
