### ISSUE TITLE
Scope should be added  Mechanics and Delay

### ISSUE THREAD

**Issue by Reyeraz** [WeaponMechanics/MechanicsMain#437]
### Description

as use bedrock model and animation make weapons,  lacking function will  effect animation to be consistent

### Configuration

```yaml
  Scope:
    Trigger: <Trigger>
    Night_Vision: <true/false>
    Pumpkin_Overlay: <true/false> # This is a WMC (Paid) feature
    Zoom_Amount: <1-10>
    Mechanics: <Mechanics>
   **Shoot_Mechanics: <Mechanics>**
    Zoom_Off:
      Trigger: <Trigger>
      Mechanics: <Mechanics>
     Shoot_Delay_After__Off_Scope: <ticks>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
