### ISSUE TITLE
Gives the player a visual arm to hold the gun

### ISSUE THREAD

**Issue by Reyeraz** [WeaponMechanics/MechanicsMain#45]
### Description

Let the player in the first person can see the other hand (maybe the left hand?) Holding a firearm
I think this can be implemented as a side-effect.
Offered for use with guns that don't use the sidearm function :)
Since I'm using version 1.14 or above, the next ones used are CustomModelData, which you can optimize
#1 My idea is to hold an item in the left hand, and make a model of the arm to change the model of the item and change the position of the model of the left hand

### Configuration

```yaml
weapons_arm:
  Default: <custom_model_data>
  Default_Hand: <custom_model_data> #1
  Scope: <custom_model_data>
  Scope_Hand: <custom_model_data>

etc
```

**Comment by CJCrafter** [comment]
```yaml
# Sometimes a player has a weapon in the offhand. Sometimes they are using the left_handed option
Show_Arm_In_Offhand:
  Left: <item serializer>
  Right: <item serializer>
  Scope_Left: <item serializer>
  Scope_Right: <item serializer>
  # also have running skin, reloading skin, etc.
  
```
