### ISSUE TITLE
Push/Pull Mechanic

### ISSUE THREAD

**Issue by alexpatten** [WeaponMechanics/MechanicsMain#451]
### Description

Hello, I was wondering if you could add a mechanic for +/- _push_. For example, if you hit someone with a bullet, allow it to push the enemy backward or pull them to you given the positive or negative _push_.

### Configuration

```yaml
Push:
  Feature_Option: <true/false>
  Force +/- 10: <amount>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature

**Comment by CJCrafter** [comment]
```yaml
<weapon>:
  Damage:
    Mechanics:
      - "Push{speed=5} @Target{}"
```
