### ISSUE TITLE
Make Bossbar persistent in Weapon_Info_Display

### ISSUE THREAD

**Issue by Reyeraz** [WeaponMechanics/MechanicsMain#46]
### Description

As the title

### Configuration

```yaml
 Boss_Bar:
        Title: <string>
        Bar_Color: <string>
        Time: <string> （I think true is ongoing）
```
