### ISSUE TITLE
OnFire ModelChange Event

### ISSUE THREAD

**Issue by SuperTNT20** [WeaponMechanics/MechanicsMain#47]
### Description

This could be enabled or a disabled feature just want to point that out. When firing the weapon if enabled by adding the "OnFire" prefix to the skins, the model of the gun will change, for example in this case a we use a muzzleflash texture. Same model but with a texture of fire to simulate a muzzle fire in front of it.

Pros: 
You can get creative by making guns glow when firing or have barrels glow red or like in my case muzzle flashes.

Cons: 
It may remove the possibility to make skins for a gun given that you would have to make separate textures for each skin when the gun shoots instead it would assign a default skin when shooting but you have lets say a blue skinned gun. By itself its a blue gun, when I fire I get a black skinned gun with muzzle texture but resorts back to being blue when not shooting.

Sounds good on paper but may be poorly executed? let me know your thoughts! 
SuperCSS20#1776

### Configuration

```yaml
Skin:
    Default:
      Custom_Model_Data: 1
    Scope:
      Custom_Model_Data: 2
    OnFire:
      Custom_Model_data: 3
    OnFireScope:
      Custom_Model_data: 4
```
