### ISSUE TITLE
Guided ammo / missiles

### ISSUE THREAD

**Issue by Nairdan** [WeaponMechanics/MechanicsMain#480]
### Description

A feature that adds guided projectiles similar to the shulker ones, but using custom item / entity data so that you can change textures / sounds, etc... it could also have trails and everything that a normal projectile would.

### Configuration

```yaml
Guided projectile:
  Feature_Option: <true/false>
  Accuracy: <amount>
  Flight_time / Flight distance: <amount>
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
