### ISSUE TITLE
Item drop on gun use/maybe kill?

### ISSUE THREAD

**Issue by Voidikins** [WeaponMechanics/MechanicsMain#485]
### Description

Id love a feature added that either drops/adds to the inventory a chosen item, in the main case being custom made (by user not creator) casings for bullets so one could use another plugin or similar to make bullet reloading. In addition to this it's be neat if you could set a specific item to maybe drop when killing a doe with a set weapon? Like with a normal set gun it drops a crushes bullet head item but maybe if you make something more like a flamethrower or laser gun you can make the dead entity drop ash, idk if this art is doable but the casing part is more the request.

### Configuration

```yaml
Fire_Drop:
  Frequency: <%amount>
  Custom_Item: <ID>
#custom item would work like how ammo does now#
  etc.
Death_Drop:
  Frequency: <%amount>
  Custom_Item: <ID>
#custom item would work like how ammo does now#
  etc.
```

### Payment (optional)

- [X] I'm willing to pay for this feature
