### ISSUE TITLE
ItemsAdder Items as ammos

### ISSUE THREAD

**Issue by Luckyyless** [WeaponMechanics/MechanicsMain#490]
### Description

So yeah, basically a really useful thing for a lot of people. Basically instead of creating the ammo in the plugins/WeaponsMechanics/Ammos/ I could just use any item I made in ItemsAdder.

### Configuration

```yaml

Let's say I have a ruby in IA and I want to use it as an ammo for my gun, then in the weapon yml it would be:

WeaponName:
  Reload:
    Ammo: itemsadder:ruby
```

### Payment (optional)

- [ ] I'm willing to pay for this feature
