### ISSUE TITLE
CSP trails

### ISSUE THREAD

**Issue by sdmaxINC** [WeaponMechanics/MechanicsMain#57]
### Description

add support Trails as it was in the Crackshotplus plugin. 

### Configuration

  Projectile:
    Projectile_Settings:
      Type: "CRIT"  or "REDSTONE"

**Comment by CJCrafter** [comment]
This is currently what the config for trails looks like.

```yaml
  Trail:
    Distance_Between_Particles: <Blocks>
    Particle_Chooser: <STOP/CLAMP, RANDOM, LOOP>
    Particles:
      Particle_0:
        Type: <FLAME/CRIT/WHATEVER>
        Color: <ColorSerializer> # Can be used with REDSTONE, MOB_SPELL, DUST_COLOR_TRANSITION
        Fade_Color: <ColorSerializer> # Can only be used with DUST_COLOR_TRANSITION particles
        Size: <Float> # Can be used with REDSTONE, or DUST_COLOR_TRANSITION
        Count: <Integer> # usually the player should not define this
        Noise: <x-y-z>
        Velocity: <x-y-z, scalar (inherit velocity * scalar)>
        Material_Data: <ItemSerializer>
      Particle_1: <Particle Serializer>
      Particle_2: <Particle Serializer>

    Shape: <NONE, SPIRAL, LIGHTNING>
    Shape_Data:
      Spirals: <Integer>
      Radius: <Blocks>
      Points: <How many particles per spiral loop>
```
