### ISSUE TITLE
Add "Sitting" to Modify_Spread_When and Modify_Recoil_When:

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#59]
### Description

Add the Sitting modifier. When the player sits on an armor stand or other entity

### Configuration

```yaml
Modify_Spread_When:
  Zooming: -5    # Make the gun more accurate when scoping
  Sneaking: -2
  Standing: 0
  Walking: 1.5
  Swimming: 1.5
  In_Midair: 4   # Player is probably jumping, so make them inaccurate
  Gliding: 6     # Player is probably moving super quick, so make them inaccurate
  Sitting: -5  
```
