### ISSUE TITLE
Testing - reload.ammo

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#6]
**What**
[Wiki link](https://github.com/DeeCaaD/WeaponMechanics-wiki/wiki/Reloading#ammo)

**Details**
- out_of_ammo triggers correctly
- exp as ammo works
- money as ammo works
- item as ammo works
- item ammo with magazines works
- filling magazine works
- unload_ammo_on_reload and ammo_per_reload works with item and magazine reload ++ exp and money

**Can you think of ways to break this feature?**
Filling doesn't work properly, items aren't consumed properly, ammo converting takes too much time

**Comment by DeeCaaD** [comment]
Fixed item ammo giving wrong amount of bullet items back when magazines were also used  
Fixed `Deny_Use_In_Crafting` with hotbar swaps

```yaml
assault_rifles:
  Ammo_Types:
    1_Ammo_Type:
      Symbol: "Type1"
      Item_Ammo:
        Bullet_Item:
          Type: DIAMOND
          Name: "&r&eYum yum"
          Deny_Use_In_Crafting: true
        Magazine_Item:
          Type: DIAMOND_BLOCK
          Name: "&r&eDiamond yum yum"
          Deny_Use_In_Crafting: true
        Ammo_Converter_Check:
          Type: true
          #Name: <true/false>
          #Lore: <true/false>
          #Enchants: <true/false>
      #Experience_As_Ammo_Cost: <experience per one ammo>
      #Money_As_Ammo_Cost: <money per one ammo>
    2_Ammo_Type:
      Symbol: "Type2"
      Item_Ammo:
        Bullet_Item:
          Type: IRON_INGOT
          Name: "&r&eYum yum"
          Deny_Use_In_Crafting: true
        Magazine_Item:
          Type: IRON_BLOCK
          Name: "&r&eDiamond yum yum"
          Deny_Use_In_Crafting: true
        Ammo_Converter_Check:
          Type: true
          #Name: <true/false>
          #Lore: <true/false>
          #Enchants: <true/false>
      #Experience_As_Ammo_Cost: <experience per one ammo>
      #Money_As_Ammo_Cost: <money per one ammo>
```
