### ISSUE TITLE
Custom amount ammo magazine

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#61]
### Description

It would be nice if the weapon could use magazines with different ammo counts and maximum ammo counts (For example, M4A1 can use 45 ammo magazine and 20 ammo)

### Configuration

```yaml
      Ammo_Types: <path to another Ammo Types key>
        1_Ammo_Type:
          Symbol: <symbol>
          Item_Ammo:
            Max_Amount_Ammo: <amount>
            Bullet_Item: <ItemSerializer>
            Magazine_Item: <ItemSerializer>
            Ammo_Converter_Check:
              Type: <true/false>
              Name: <true/false>
              Lore: <true/false>
              Enchants: <true/false>
            Experience_As_Ammo_Cost: <experience per one ammo>
            Money_As_Ammo_Cost: <money per one ammo>
          2_Ammo_Type: <etc.>
```
