### ISSUE TITLE
Custom Ammo types

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#62]
### Description

Add the ability to use different types of cartridges, armor-piercing, incendiary or explosive. (The player could create such types himself). 

### Configuration

```yaml
  Reload:
    Trigger: <trigger serializer>
    Magazine_Size: <amount>
    Ammo_Per_Reload: <amount>
    Unload_Ammo_On_Reload: <true/false>
    Reload_Duration: <ticks>
    Start_Mechanics: <MechanicsSerializer>
    Finish_Mechanics: <MechanicsSerializer>
    Ammo:
      Out_Of_Ammo: <MechanicsSerializer>
      Ammo_Type_Switch:
        Trigger: <TriggerSerializer>
        Mechanics: <MechanicsSerializer>
      Ammo_Types: <path to another Ammo Types key>
        1_Ammo_Type:
          Symbol: <symbol>
          Item_Ammo:
            Bullet_Item: <ItemSerializer>
            Magazine_Item: <ItemSerializer>
            Ammo_Converter_Check:
              Type: <true/false>
              Name: <true/false>
              Lore: <true/false>
              Enchants: <true/false>
          Features:
            Damage: <amount>
            Give_Potion_Effect:s <true/false>
            Potion_Effects:
              - <PotionEffectType>-<Duration>-<Level>
              - <PotionEffectType>-<Duration>-<Level>-<Allow Particles>-<Extra Particles>-<Icon>
              - <etc.>
            Explosion: <true/false>
            Explosion_size: <amount> #How big is this explosion from a bullet
            Explosion_Damage: <amount>
            Explosion_Other: <true/false> #can other players take damage from the bullet explosion
            Explosion_Sound: 
              - <sound>-<volume>-<pitch>
              - <sound>-<volume>-<pitch>-<delay>-<pitchNoise>
              - custom:<sound>-<volume>-<pitch>
              - custom:<sound>-<volume>-<pitch>-<delay>-<pitchNoise>
          Experience_As_Ammo_Cost: <experience per one ammo>
          Money_As_Ammo_Cost: <money per one ammo>
        2_Ammo_Type: <etc.>
```
