### ISSUE TITLE
Changing Spread bounds based on Player Action

### ISSUE THREAD

**Issue by marijay1** [WeaponMechanics/MechanicsMain#67]
### Description

The ability to set Spread Bounds based on the actions of the player. (running, jumping, zooming, etc.)

### Configuration

```
Spread:
    Changing_Spread:
        Bounds:
            Changing_Minimum:
                Always: <Minimum Amount>
                Zooming: <Minimum Amount>
                Sneaking: <Minimum Amount>
                Standing: <Minimum Amount>
                Walking: <Minimum Amount>
                Riding: <Minimum Amount>
                Sprinting: <Minimum Amount>
                Dual_Wielding: <Minimum Amount>
                Swimming: <Minimum Amount>
                In_Midair: <Minimum Amount>
                Gliding: <Minimum Amount>
            Changing_Maximum:
                Always: <Maximum Amount>
                Zooming: <Maximum Amount>
                Sneaking: <Maximum Amount>
                Standing: <Maximum Amount>
                Walking: <Maximum Amount>
                Riding: <Maximum Amount>
                Sprinting: <Maximum Amount>
                Dual_Wielding: <Maximum Amount>
                Swimming: <Maximum Amount>
                In_Midair: <Maximum Amount>
                Gliding: <Maximum Amount>
```
