### ISSUE TITLE
Gun Animation

### ISSUE THREAD

**Issue by Jellychicken** [WeaponMechanics/MechanicsMain#68]
### Description

Adds the ability to use gun animation.
This animation feature need resourcepack.
if anyone use this feature, you should add 9.6 to translation y of 3d model's display.

example:
https://streamable.com/ovm4cy
https://streamable.com/a5rhef

### Configuration

```yaml
Animations:
  Use_Animation: <true/false> #if this value is true, when player swap item to wm gun, system will give player mining fatigue 200 for max seconds to delete minecraft own item swap motion
  Shooting:
    Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
  Reloading:
    Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
    Open_Animation_List: #execute animation when reloading gun without left bullets
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
  Scoping:
    Duration: <ticks>
    Zoom_Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
    Zoom_Off_Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
    Zoom_Shoot_Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
  Firearms:
    Open_Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
    Close_Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
  Sprint:
    Sprint_Delay: <ticks>
    Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
  Swap:
    Duration: <ticks>
    Animation_List:
    - <item>-<custommodeldata>-<ticks>
    - <etc.>
    #Swap_Sound_List:
    #- <sound>-<volume>-<pitch>
    #- <sound>-<volume>-<pitch>-<delay>-<pitchNoise>
    #- custom:<sound>-<volume>-<pitch>
    #- custom:<sound>-<volume>-<pitch>-<delay>-<pitchNoise>
    #- <etc.>
    
```
