### ISSUE TITLE
Play multiple sounds depending on distance

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#70]
### Description

Add the ability to use multiple sounds at different distances.

For example, the sound of a shot at a distance of 50 will be loud, at a distance of 100 it will be quiet

### Configuration

```yaml
Mechanics:
  Sounds:
  - <sound>-<volume>-<pitch>-<range_min>:<range_max>
  - <range>-<volume>-<pitch>-<delay>-<pitchNoise>-<range_min>:<range_max>
  - custom:<sound>-<volume>-<pitch>-<range_min>:<range_max>
  - custom:<sound>-<volume>-<pitch>-<delay>-<pitchNoise>-<range_min>:<range_max>
  - <etc.>
  for example:
  - "custom:guns:ak47shoot-1-1-20:50" 
  - "custom:guns:ak47shoot2-1-1-51:70"
  - "custom:guns:ak47shoot2-1-1-71:100"          
```
