### ISSUE TITLE
Sneaking to scope

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#79]
### Description

Hold down Sneak to aim.

### Configuration

```yaml
  Scope:
    Trigger:
      Main_Hand: "HOLD_SNEAK"
      Off_Hand: "HOLD_SNEAK"
```

**Comment by DeeCaaD** [comment]
Already possible

```yml
Scope:
  Trigger:
    Main_Hand: "START_SNEAK"
    Off_Hand: "START_SNEAK"
  Zoom_Off:
    Trigger:
      Main_Hand: "END_SNEAK"
      Off_Hand: "END_SNEAK"
```
