### ISSUE TITLE
pumpkin on zoom

### ISSUE THREAD

**Issue by DrC4pivara** [WeaponMechanics/MechanicsMain#82]
### Description

same thing as crackshotplus

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```
