### ISSUE TITLE
Bullet holes

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#84]
### Description

Bullet holes when hitting a block using Armor stand.

### Configuration

```yaml
Bullet_holes:
  Enable: <true/false>
  CustomModelData: <int>
  Ticks_to_remove: <ticks>
```
