### ISSUE TITLE
About Reloading Weapons

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#85]
### Description

**If I spam the Q Key, a new reload sound will come before the reload sound ends. By the way, if I go directly to another slot while reloading, the reload sound continues until it ends. In other words, if the reload is canceled, a feature is required that will stop the previous sound.**

https://user-images.githubusercontent.com/89253304/165473979-bb6dc26c-025e-4388-8513-6adb5783df17.mp4

### It should work automatically.

**Comment by CJCrafter** [comment]
Spigot has methods for stopping sounds (both custom and normal). See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#stopSound(java.lang.String)

**Comment by CJCrafter** [comment]
While it is possible to stop sounds after they begin to play, our code prevents us from easily accomplishing this (Without some amount of rewriting). We recommend using 2 short sounds for `start` and `end`. The default weapons do this already:
```yaml
    Start_Mechanics:
      Sounds:
        - "custom:reload.start.normal-0.5-1-0-0.1"
    Finish_Mechanics:
      Sounds:
        - "custom:reload.end.normal-0.5-1-0-0.1"
```

If you need this feature still, join our discord and ask about paying for this to be added.
