### ISSUE TITLE
CustomModelData for ammo

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#86]
### Description

CustomModelData for ammunition.

### Configuration

```yaml
 Ammo_Types: <path to another Ammo Types key>
        1_Ammo_Type:
          Symbol: <symbol>
          Item_Ammo:
            Bullet_Item: <ItemSerializer>
            CustomModelData: <number>

```
