### ISSUE TITLE
Per-Weapon Kill/Death Messages

### ISSUE THREAD

**Issue by WungaWunga** [WeaponMechanics/MechanicsMain#87]
### Description

Title says it all. Right now, the only way to create a custom kill message is through the shooter/victim mechanics of a gun's "kill" event. This works, but killing mobs also triggers this event, potentially flooding chat with meaningless death messages (see screenshot for an example). I'd like to see a dedicated kill message for PvP events. If it's not too difficult to add, having separate messages for player vs entity, player vs citizens npc, and explosive deaths would be even better:
"Steve finished off the Spider Queen with a Remington." (PvE death message)
"Notch scorched Steve with an Olympia." (fire-death while fighting Olympia)
"Dinnerbone blew up from a grenade launched by Alex." (explosive death)

### Configuration

```yaml
Kill_Messages:
  Enabled: <true/false>
  Count_Explosive_Deaths: <true/false>
  Count_Burn_Deaths: <true/false>
  Count_Drop_Deaths: <true/false>
  Player_Kill_Message: <string>
  Entity_Kill_Message: <string>
  Citizens_Kill_Message: <string>
  
```
![2022-04-26_14 34 38](https://user-images.githubusercontent.com/104462476/165597128-490d946c-8351-4f2b-a6d7-84e3d78f3c6d.png)

**Comment by CJCrafter** [comment]
Perhaps instead of using Mechanics, we have a killfeed option?

```yaml
AK-47:
  Killfeed:
    Only_Players: true # defaults to true
    Generic:
    - "%victim% was shot by %shooter%"
    Explosion: # if this list is empty, defaults to generic
   -  "%victim% was nuked by %shooter%"
```
