### ISSUE TITLE
New cancel event

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#93]
### Description

Cancel only break block event

### Configuration

```yaml
    Cancel:
      Break_blocks: <true/false>
      Block_Interactions: <true/false>
      Item_Interactions: <true/false>
      Drop_Item: <true/false>
      Swap_Hands: <true/false>
      Arm_Swing_Animation: <true/false>
```
