### ISSUE TITLE
Add new No_Ammo skins

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/MechanicsMain#96]
### Description

Add new No_Ammo skins

### Configuration

```yaml
  Skin:
    Default:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Default_No_Ammo:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Scope:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Scope_No_Ammo:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Scope_<number>:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Scope_No_Ammo_<number>:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Reload:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Reload_No_Ammo:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Sprint:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
    Sprint_No_Ammo:
      Type: <Material>
      Legacy_Data: <Integer>
      Custom_Model_Data: <Integer>
      Durability: <Integer>
```
